### ISSUE TITLE
Something went wrong InvalidEndpointError: Invalid endPoint - AWS S3

### ISSUE THREAD

**Issue by jrCleber** [baptisteArno/typebot.io#1048]
**Version:** 2.19.1

Hello!
While trying to upload a file, I am receiving the following error:
```sh
Something went wrong InvalidEndpointError: Invalid endPoint : arn:aws:s3:us-east-1:account_id:accesspoint/typebot
    at new TypedClient (/app/apps/builder/.next/server/chunks/3174.js:11:177574)
    ... 8 lines matching cause stack trace ...
    at async callRecursive (file:///app/node_modules/.pnpm/@trpc+server@10.40.0/node_modules/@trpc/server/dist/index.mjs:456:32) {
  code: 'INTERNAL_SERVER_ERROR',
  name: 'TRPCError',
  [cause]: InvalidEndpointError: Invalid endPoint : arn:aws:s3:us-east-1:708621784799:accesspoint/typebot
      at new TypedClient (/app/apps/builder/.next/server/chunks/3174.js:11:177574)
      at new Client (/app/apps/builder/.next/server/chunks/3174.js:15:23602)
      at generatePresignedPostPolicy (/app/apps/builder/.next/server/chunks/6468.js:1:473)
      at /app/apps/builder/.next/server/chunks/533.js:1:66962
      at async resolveMiddleware (file:///app/node_modules/.pnpm/@trpc+server@10.40.0/node_modules/@trpc/server/dist/index.mjs:420:30)
      at async callRecursive (file:///app/node_modules/.pnpm/@trpc+server@10.40.0/node_modules/@trpc/server/dist/index.mjs:456:32)
      at async outputMiddleware (file:///app/node_modules/.pnpm/@trpc+server@10.40.0/node_modules/@trpc/server/dist/index.mjs:301:24)
      at async callRecursive (file:///app/node_modules/.pnpm/@trpc+server@10.40.0/node_modules/@trpc/server/dist/index.mjs:456:32)
      at async callRecursive (file:///app/node_modules/.pnpm/@trpc+server@10.40.0/node_modules/@trpc/server/dist/index.mjs:456:32)
      at async callRecursive (file:///app/node_modules/.pnpm/@trpc+server@10.40.0/node_modules/@trpc/server/dist/index.mjs:456:32)
}
```

The environment variables are configured like this:
```yaml
      - S3_ACCESS_KEY=${public_key}
      - S3_SECRET_KEY=${secret_key}
      - S3_BUCKET=typebotcodechat
      - S3_ENDPOINT=arn:aws:s3:us-east-1:708621784799:accesspoint/typebot
```

How can I fix this error?

**Comment by baptisteArno** [comment]
AWS creds should look like this:

```
S3_ACCESS_KEY=...
S3_SECRET_KEY=...
S3_BUCKET=typebot
S3_ENDPOINT=s3.eu-west-3.amazonaws.com
S3_REGION=eu-west-3
```
