### ISSUE TITLE
next/image components not correctly fetching images in some self-hosted instances

### ISSUE THREAD

**Issue by baptisteArno** [baptisteArno/typebot.io#1083]

**Comment by baptisteArno** [comment]
![image](https://github.com/baptisteArno/typebot.io/assets/16015833/28b069ad-7280-42a2-a021-7023c2fde9f9)

**Comment by baptisteArno** [comment]
Error is:

```
2023-12-05T00:38:58.320328656Z upstream image response failed for /_next/static/media/light-mode.180b9fdd.png TypeError: fetch failed
2023-12-05T00:38:58.320356156Z     at Object.fetch (node:internal/deps/undici/undici:11730:11)
2023-12-05T00:38:58.320359404Z     at async invokeRequest (/app/node_modules/.pnpm/next@13.5.4_@babel+core@7.22.9_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/lib/server-ipc/invoke-request.js:16:12)
2023-12-05T00:38:58.320362144Z     at async /app/node_modules/.pnpm/next@13.5.4_@babel+core@7.22.9_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/next-server.js:362:35
2023-12-05T00:38:58.320364805Z     at async imageOptimizer (/app/node_modules/.pnpm/next@13.5.4_@babel+core@7.22.9_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/image-optimizer.js:537:13)
2023-12-05T00:38:58.320367461Z     at async cacheEntry.imageResponseCache.get.incrementalCache (/app/node_modules/.pnpm/next@13.5.4_@babel+core@7.22.9_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/next-server.js:517:61)
2023-12-05T00:38:58.320383163Z     at async /app/node_modules/.pnpm/next@13.5.4_@babel+core@7.22.9_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/response-cache/index.js:102:36 {
2023-12-05T00:38:58.320385814Z   cause: InvalidArgumentError: invalid connection header
2023-12-05T00:38:58.320388213Z       at processHeader (/app/node_modules/.pnpm/next@13.5.4_@babel+core@7.22.9_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/undici/index.js:1:102994)
2023-12-05T00:38:58.320390726Z       at new Request (/app/node_modules/.pnpm/next@13.5.4_@babel+core@7.22.9_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/undici/index.js:1:100295)
2023-12-05T00:38:58.320393226Z       at [dispatch] (/app/node_modules/.pnpm/next@13.5.4_@babel+core@7.22.9_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/undici/index.js:1:64352)
2023-12-05T00:38:58.320395708Z       at Intercept (/app/node_modules/.pnpm/next@13.5.4_@babel+core@7.22.9_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/undici/index.js:2:93153)
2023-12-05T00:38:58.320408200Z       at [Intercepted Dispatch] (/app/node_modules/.pnpm/next@13.5.4_@babel+core@7.22.9_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/undici/index.js:1:115359)
2023-12-05T00:38:58.320411164Z       at Client.dispatch (/app/node_modules/.pnpm/next@13.5.4_@babel+core@7.22.9_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/undici/index.js:1:115591)
2023-12-05T00:38:58.320413462Z       at [dispatch] (/app/node_modules/.pnpm/next@13.5.4_@babel+core@7.22.9_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/undici/index.js:2:264035)
2023-12-05T00:38:58.320415649Z       at [Intercepted Dispatch] (/app/node_modules/.pnpm/next@13.5.4_@babel+core@7.22.9_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/undici/index.js:1:115258)
2023-12-05T00:38:58.320417855Z       at Pool.dispatch (/app/node_modules/.pnpm/next@13.5.4_@babel+core@7.22.9_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/undici/index.js:1:115591)
2023-12-05T00:38:58.320420064Z       at [dispatch] (/app/node_modules/.pnpm/next@13.5.4_@babel+core@7.22.9_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/undici/index.js:1:29874) {
2023-12-05T00:38:58.320422248Z     code: 'UND_ERR_INVALID_ARG'
2023-12-05T00:38:58.320424318Z   }
2023-12-05T00:38:58.320426319Z }
```

**Comment by uhlhosting** [comment]
@baptisteArno don't your app stack has a cli to clean assets cache and regenerate assets maybe?

**Comment by uhlhosting** [comment]
This is ARC/Chromium screen:

<img width="1680" alt="image" src="https://github.com/baptisteArno/typebot.io/assets/6324047/4718ef3f-e868-411e-9999-b1038d921761">
