### ISSUE TITLE
Missing Database Migration after Upgrade

### ISSUE THREAD

**Issue by luizeof** [baptisteArno/typebot.io#1131]
Hello @baptisteArno I hope 2024 is a year of health, achievements and success in your life and your family.

I upgraded the Docker image to 2.21.2 and encountered this error.

Is there any command to "force" the database migrations to run?

```
Something went wrong PrismaClientKnownRequestError: 
Invalid `prisma.workspace.findFirst()` invocation:
The column `Workspace.isVerified` does not exist in the current database.
    at zr.handleRequestError (/app/node_modules/.pnpm/@prisma+client@5.0.0_prisma@5.0.0/node_modules/@prisma/client/runtime/library.js:122:8308)
    ... 8 lines matching cause stack trace ...
    at async callRecursive (file:///app/node_modules/.pnpm/@trpc+server@10.40.0/node_modules/@trpc/server/dist/index.mjs:456:32) {
  code: 'INTERNAL_SERVER_ERROR',
  name: 'TRPCError',
  [cause]: PrismaClientKnownRequestError: 
  Invalid `prisma.workspace.findFirst()` invocation:
  
  
  The column `Workspace.isVerified` does not exist in the current database.
      at zr.handleRequestError (/app/node_modules/.pnpm/@prisma+client@5.0.0_prisma@5.0.0/node_modules/@prisma/client/runtime/library.js:122:8308)
      at zr.handleAndLogRequestError (/app/node_modules/.pnpm/@prisma+client@5.0.0_prisma@5.0.0/node_modules/@prisma/client/runtime/library.js:122:7697)
      at zr.request (/app/node_modules/.pnpm/@prisma+client@5.0.0_prisma@5.0.0/node_modules/@prisma/client/runtime/library.js:122:7307)
      at async /app/apps/builder/.next/server/chunks/4172.js:1:76302
      at async resolveMiddleware (file:///app/node_modules/.pnpm/@trpc+server@10.40.0/node_modules/@trpc/server/dist/index.mjs:420:30)
      at async callRecursive (file:///app/node_modules/.pnpm/@trpc+server@10.40.0/node_modules/@trpc/server/dist/index.mjs:456:32)
      at async outputMiddleware (file:///app/node_modules/.pnpm/@trpc+server@10.40.0/node_modules/@trpc/server/dist/index.mjs:301:24)
      at async callRecursive (file:///app/node_modules/.pnpm/@trpc+server@10.40.0/node_modules/@trpc/server/dist/index.mjs:456:32)
      at async callRecursive (file:///app/node_modules/.pnpm/@trpc+server@10.40.0/node_modules/@trpc/server/dist/index.mjs:456:32)
      at async callRecursive (file:///app/node_modules/.pnpm/@trpc+server@10.40.0/node_modules/@trpc/server/dist/index.mjs:456:32) {
    code: 'P2022',
    clientVersion: '5.0.0',
    meta: { column: 'Workspace.isVerified' }
  }
}
```

**Comment by baptisteArno** [comment]
It seems the database schema migration did not correctly succeeded when you restarted the stack? Can you get logs about that?

**Comment by luizeof** [comment]
> It seems the database schema migration did not correctly succeeded when you restarted the stack? Can you get logs about that?

after restarting the services:


```
- event [next-runtime-env] read environment variables prefixed with 'NEXT_PUBLIC_' from process.env.
- ready [next-runtime-env] wrote browser runtime environment variables to '/app/apps/builder/public/__ENV.js'.
Waiting for 15s for database to be ready...
Prisma schema loaded from packages/prisma/postgresql/schema.prisma
Datasource "db": PostgreSQL database "typebots3aytvq", schema "public" at "postgres:5432"
62 migrations found in prisma/migrations

Error: P3009
migrate found failed migrations in the target database, new migrations will not be applied. Read more about how to resolve migration issues in a production database: https://pris.ly/d/migrate-resolve
The `20231208172001_add_risk_level` migration started at 2024-01-03 14:16:45.981004 UTC failed
   ▲ Next.js 14.0.3
   - Local:        http://localhost:3000
   - Network:      http://0.0.0.0:3000
 ✓ Ready in 1531ms
```

**Comment by baptisteArno** [comment]
Strange! Can you find the error priori to this?

Here it says that it previously failed, can you find the logs of when it failed?

**Comment by baptisteArno** [comment]
You will need to fix it: https://www.prisma.io/docs/orm/prisma-migrate/workflows/patching-and-hotfixing#failed-migration
