### ISSUE TITLE
All recipients were rejected

### ISSUE THREAD

**Issue by mihha** [baptisteArno/typebot.io#128]
Hi,

I am trying to use the latest version in docker environment, but email login is not working

When I check builder docker logs, I can see the following:
```
[next-auth][error][SIGNIN_EMAIL_ERROR] 
https://next-auth.js.org/errors#signin_email_error Can't send mail - all recipients were rejected: 554 5.7.1 Service unavailable; Sender address [mihha@mihha-mail.xyz] blocked using dbl.spamhaus.org; Error: open resolver; https://www.spamhaus.org/returnc/pub/2400:cb00:537:1024::ac47:8126 {
  error: {
    message: "Can't send mail - all recipients were rejected: 554 5.7.1 Service unavailable; Sender address [mihha@mihha-mail.xyz] blocked using dbl.spamhaus.org; Error: open resolver; https://www.spamhaus.org/returnc/pub/2400:cb00:537:1024::ac47:8126",
    stack: "Error: Can't send mail - all recipients were rejected: 554 5.7.1 Service unavailable; Sender address [mihha@mihha-mail.xyz] blocked using dbl.spamhaus.org; Error: open resolver; https://www.spamhaus.org/returnc/pub/2400:cb00:537:1024::ac47:8126\n" +
      '    at SMTPConnection._formatError (/app/node_modules/.pnpm/nodemailer@6.7.8/node_modules/nodemailer/lib/smtp-connection/index.js:787:19)\n' +
      '    at SMTPConnection._actionRCPT (/app/node_modules/.pnpm/nodemailer@6.7.8/node_modules/nodemailer/lib/smtp-connection/index.js:1629:28)\n' +
      '    at SMTPConnection.<anonymous> (/app/node_modules/.pnpm/nodemailer@6.7.8/node_modules/nodemailer/lib/smtp-connection/index.js:1582:30)\n' +
      '    at SMTPConnection._processResponse (/app/node_modules/.pnpm/nodemailer@6.7.8/node_modules/nodemailer/lib/smtp-connection/index.js:950:20)\n' +
      '    at SMTPConnection._onData (/app/node_modules/.pnpm/nodemailer@6.7.8/node_modules/nodemailer/lib/smtp-connection/index.js:752:14)\n' +
      '    at SMTPConnection._onSocketData (/app/node_modules/.pnpm/nodemailer@6.7.8/node_modules/nodemailer/lib/smtp-connection/index.js:191:44)\n' +
      '    at TLSSocket.emit (node:events:513:28)\n' +
      '    at TLSSocket.emit (node:domain:552:15)\n' +
      '    at addChunk (node:internal/streams/readable:324:12)\n' +
      '    at readableAddChunk (node:internal/streams/readable:297:9)',
    name: 'Error'
  },
  providerId: 'email',
  message: "Can't send mail - all recipients were rejected: 554 5.7.1 Service unavailable; Sender address [mihha@mihha-mail.xyz] blocked using dbl.spamhaus.org; Error: open resolver; https://www.spamhaus.org/returnc/pub/2400:cb00:537:1024::ac47:8126"
}
```

My email server is working correctly and checking the SpamHaus for the domain returns that everything is OK

![image](https://user-images.githubusercontent.com/3791124/190362490-5941a5a9-471d-4023-aa77-0a664f8cdbce.png)

I have to say that before you introduced SMTP_SECURE environment parameter, things were looking good, and I could use email signup without any issues

Is there anything else I can check or set to resolve this problem?

**Comment by mihha** [comment]
I have figured it, so no need for a reply

Sorry to bother you all with this
