### ISSUE TITLE
Error while using variables in self hosted typebot

### ISSUE THREAD

**Issue by cristianormoraes** [baptisteArno/typebot.io#1678]
When I use an "variable" with fixed value, I cant run the flow, I got this error:

"Error! Could not reach server. Check your connection. {}"

![Screenshot_3](https://github.com/user-attachments/assets/758753fa-9039-4ef3-acbc-08d08ebf12fb)

I checked the post to /api/v1/typebots/clzclrmak000y14h0ayr4bivm/preview/startChat 

result is 502 Bad Gateway

**Comment by baptisteArno** [comment]
Hey,

Can you clearly describe it by following this template:

1. Steps to reproduce
2. What's happening
3. What were you expecting

It's even better if you can provide a screen recording.

This ultimately allow me to reproduce the bug so that I can fix it properly.

**Comment by cristianormoraes** [comment]
I did a scrren record, first I tried to run at typebot.io and works fine, but in self hosted did a described error, pls check full video.

https://github.com/user-attachments/assets/1ff0701b-21a3-4aa7-b270-8f511f536db2

**Comment by cristianormoraes** [comment]
> Hey,
> 
> Can you clearly describe it by following this template:
> 
> 1. Steps to reproduce
> 2. What's happening
> 3. What were you expecting
> 
> It's even better if you can provide a screen recording.
> 
> This ultimately allow me to reproduce the bug so that I can fix it properly.

Typebot need any special permission at instalation?

**Comment by baptisteArno** [comment]
Can you provide the server logs? There should be a clear error there.

If you are self-hosting it with docker. Type this command in your terminal:

```sh
docker-compose logs
```

Paste all the logs here so that we can help you properly!

**Comment by cristianormoraes** [comment]
Manual installation, not using docker :(

**Comment by baptisteArno** [comment]
Feel free to re-open whenever you have logs to paste

**Comment by cristianormoraes** [comment]
I got the log with the error while runinng viewer:



> viewer@0.1.0 start /var/www/typebot.io/apps/viewer
> dotenv -e ./.env -e ../../.env -- next start "-p" "4001"

   ▲ Next.js 14.1.0
   - Local:        http://localhost:4001

- event [next-runtime-env] read environment variables prefixed with 'NEXT_PUBLIC_' from process.env.
- ready [next-runtime-env] wrote browser runtime environment variables to '/var/www/typebot.io/apps/viewer/public/__ENV.js'.
 ⚠ "next start" does not work with "output: standalone" configuration. Use "node .next/standalone/server.js" instead.
 ✓ Ready in 702ms
Error: /var/www/typebot.io/node_modules/.pnpm/isolated-vm@5.0.1/node_modules/isolated-vm/out/isolated_vm.node: undefined symbol: _ZN2v815ValueSerializer8Delegate24AdoptSharedValueConveyorEPNS_7IsolateEONS_19SharedValueConveyorE
    at Module._extensions..node (node:internal/modules/cjs/loader:1460:18)
    at Module.load (node:internal/modules/cjs/loader:1203:32)
    at Module._load (node:internal/modules/cjs/loader:1019:12)
    at Module.require (node:internal/modules/cjs/loader:1231:19)
    at mod.require (/var/www/typebot.io/node_modules/.pnpm/next@14.1.0_@babel+core@7.22.9_@opentelemetry+api@1.9.0_react-dom@18.2.0_react@18.2.0__react@18.2.0/node_modules/next/dist/server/require-hook.js:65:28)
    at require (node:internal/modules/helpers:177:18)
    at Object.<anonymous> (/var/www/typebot.io/node_modules/.pnpm/isolated-vm@5.0.1/node_modules/isolated-vm/isolated-vm.js:1:18)
    at Module._compile (node:internal/modules/cjs/loader:1364:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
    at Module.load (node:internal/modules/cjs/loader:1203:32) {
  code: 'ERR_DLOPEN_FAILED'
}
Error: /var/www/typebot.io/node_modules/.pnpm/isolated-vm@5.0.1/node_modules/isolated-vm/out/isolated_vm.node: undefined symbol: _ZN2v815ValueSerializer8Delegate24AdoptSharedValueConveyorEPNS_7IsolateEONS_19SharedValueConveyorE
    at Module._extensions..node (node:internal/modules/cjs/loader:1460:18)
    at Module.load (node:internal/modules/cjs/loader:1203:32)
    at Module._load (node:internal/modules/cjs/loader:1019:12)
    at Module.require (node:internal/modules/cjs/loader:1231:19)
    at mod.require (/var/www/typebot.io/node_modules/.pnpm/next@14.1.0_@babel+core@7.22.9_@opentelemetry+api@1.9.0_react-dom@18.2.0_react@18.2.0__react@18.2.0/node_modules/next/dist/server/require-hook.js:65:28)
    at require (node:internal/modules/helpers:177:18)
    at Object.<anonymous> (/var/www/typebot.io/node_modules/.pnpm/isolated-vm@5.0.1/node_modules/isolated-vm/isolated-vm.js:1:18)
    at Module._compile (node:internal/modules/cjs/loader:1364:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
    at Module.load (node:internal/modules/cjs/loader:1203:32) {
  code: 'ERR_DLOPEN_FAILED'
}
Error: /var/www/typebot.io/node_modules/.pnpm/isolated-vm@5.0.1/node_modules/isolated-vm/out/isolated_vm.node: undefined symbol: _ZN2v815ValueSerializer8Delegate24AdoptSharedValueConveyorEPNS_7IsolateEONS_19SharedValueConveyorE
    at Module._extensions..node (node:internal/modules/cjs/loader:1460:18)
    at Module.load (node:internal/modules/cjs/loader:1203:32)
    at Module._load (node:internal/modules/cjs/loader:1019:12)
    at Module.require (node:internal/modules/cjs/loader:1231:19)
    at mod.require (/var/www/typebot.io/node_modules/.pnpm/next@14.1.0_@babel+core@7.22.9_@opentelemetry+api@1.9.0_react-dom@18.2.0_react@18.2.0__react@18.2.0/node_modules/next/dist/server/require-hook.js:65:28)
    at require (node:internal/modules/helpers:177:18)
    at Object.<anonymous> (/var/www/typebot.io/node_modules/.pnpm/isolated-vm@5.0.1/node_modules/isolated-vm/isolated-vm.js:1:18)
    at Module._compile (node:internal/modules/cjs/loader:1364:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
    at Module.load (node:internal/modules/cjs/loader:1203:32) {
  code: 'ERR_DLOPEN_FAILED'
}
Error: /var/www/typebot.io/node_modules/.pnpm/isolated-vm@5.0.1/node_modules/isolated-vm/out/isolated_vm.node: undefined symbol: _ZN2v815ValueSerializer8Delegate24AdoptSharedValueConveyorEPNS_7IsolateEONS_19SharedValueConveyorE
    at Module._extensions..node (node:internal/modules/cjs/loader:1460:18)
    at Module.load (node:internal/modules/cjs/loader:1203:32)
    at Module._load (node:internal/modules/cjs/loader:1019:12)
    at Module.require (node:internal/modules/cjs/loader:1231:19)
    at mod.require (/var/www/typebot.io/node_modules/.pnpm/next@14.1.0_@babel+core@7.22.9_@opentelemetry+api@1.9.0_react-dom@18.2.0_react@18.2.0__react@18.2.0/node_modules/next/dist/server/require-hook.js:65:28)
    at require (node:internal/modules/helpers:177:18)
    at Object.<anonymous> (/var/www/typebot.io/node_modules/.pnpm/isolated-vm@5.0.1/node_modules/isolated-vm/isolated-vm.js:1:18)
    at Module._compile (node:internal/modules/cjs/loader:1364:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
    at Module.load (node:internal/modules/cjs/loader:1203:32) {
  code: 'ERR_DLOPEN_FAILED'
}
Error: /var/www/typebot.io/node_modules/.pnpm/isolated-vm@5.0.1/node_modules/isolated-vm/out/isolated_vm.node: undefined symbol: _ZN2v815ValueSerializer8Delegate24AdoptSharedValueConveyorEPNS_7IsolateEONS_19SharedValueConveyorE
    at Module._extensions..node (node:internal/modules/cjs/loader:1460:18)
    at Module.load (node:internal/modules/cjs/loader:1203:32)
    at Module._load (node:internal/modules/cjs/loader:1019:12)
    at Module.require (node:internal/modules/cjs/loader:1231:19)
    at mod.require (/var/www/typebot.io/node_modules/.pnpm/next@14.1.0_@babel+core@7.22.9_@opentelemetry+api@1.9.0_react-dom@18.2.0_react@18.2.0__react@18.2.0/node_modules/next/dist/server/require-hook.js:65:28)
    at require (node:internal/modules/helpers:177:18)
    at Object.<anonymous> (/var/www/typebot.io/node_modules/.pnpm/isolated-vm@5.0.1/node_modules/isolated-vm/isolated-vm.js:1:18)
    at Module._compile (node:internal/modules/cjs/loader:1364:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
    at Module.load (node:internal/modules/cjs/loader:1203:32) {
  code: 'ERR_DLOPEN_FAILED'
}
Error: /var/www/typebot.io/node_modules/.pnpm/isolated-vm@5.0.1/node_modules/isolated-vm/out/isolated_vm.node: undefined symbol: _ZN2v815ValueSerializer8Delegate24AdoptSharedValueConveyorEPNS_7IsolateEONS_19SharedValueConveyorE
    at Module._extensions..node (node:internal/modules/cjs/loader:1460:18)
    at Module.load (node:internal/modules/cjs/loader:1203:32)
    at Module._load (node:internal/modules/cjs/loader:1019:12)
    at Module.require (node:internal/modules/cjs/loader:1231:19)
    at mod.require (/var/www/typebot.io/node_modules/.pnpm/next@14.1.0_@babel+core@7.22.9_@opentelemetry+api@1.9.0_react-dom@18.2.0_react@18.2.0__react@18.2.0/node_modules/next/dist/server/require-hook.js:65:28)
    at require (node:internal/modules/helpers:177:18)
    at Object.<anonymous> (/var/www/typebot.io/node_modules/.pnpm/isolated-vm@5.0.1/node_modules/isolated-vm/isolated-vm.js:1:18)
    at Module._compile (node:internal/modules/cjs/loader:1364:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
    at Module.load (node:internal/modules/cjs/loader:1203:32) {
  code: 'ERR_DLOPEN_FAILED'
}
 ⨯ Error: /var/www/typebot.io/node_modules/.pnpm/isolated-vm@5.0.1/node_modules/isolated-vm/out/isolated_vm.node: undefined symbol: _ZN2v815ValueSerializer8Delegate24AdoptSharedValueConveyorEPNS_7IsolateEONS_19SharedValueConveyorE
    at Module._extensions..node (node:internal/modules/cjs/loader:1460:18)
    at Module.load (node:internal/modules/cjs/loader:1203:32)
    at Module._load (node:internal/modules/cjs/loader:1019:12)
    at Module.require (node:internal/modules/cjs/loader:1231:19)
    at mod.require (/var/www/typebot.io/node_modules/.pnpm/next@14.1.0_@babel+core@7.22.9_@opentelemetry+api@1.9.0_react-dom@18.2.0_react@18.2.0__react@18.2.0/node_modules/next/dist/server/require-hook.js:65:28)
    at require (node:internal/modules/helpers:177:18)
    at Object.<anonymous> (/var/www/typebot.io/node_modules/.pnpm/isolated-vm@5.0.1/node_modules/isolated-vm/isolated-vm.js:1:18)
    at Module._compile (node:internal/modules/cjs/loader:1364:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
    at Module.load (node:internal/modules/cjs/loader:1203:32) {
  code: 'ERR_DLOPEN_FAILED'
}
