### ISSUE TITLE
linking bots to whatsapp is not working anymore after setting a display name for my number in meta

### ISSUE THREAD

**Issue by MotazHakim** [baptisteArno/typebot.io#1896]
**Describe the bug**
i've installed typebot via docker
and i've many bots, and i've shared one with whatsapp business , created the app in META and set the user permission and everything and the bot was working great on whatsapp with no issue at all, and after couple days in META i've applied for display name for the whatsapp number i've have, and it got approved, and i've used REST API to register the number using this [META docs ](https://developers.facebook.com/docs/whatsapp/cloud-api/reference/registration/) and i've got the Success response, and i've found that my number in whatsapp have official name, and i've change nothing on typebot or META, then ii've found that that whatsapp number is not replying to the bot !!

so i've tested the TEST NUMBER the meta provide and linked it with typebot and sent a message to that TEST number, and i got reply from the BOT !, so i've linked again back the main number i'm using, and sent a message to it , and NO REPLY !

and in typebot-viewer logs i've found this every time i send a message to the main whatsapp business number 

```
Unknown WhatsApp error: ReferenceError: origin is not defined
    at E (/app/apps/viewer/.next/server/chunks/600.js:108:3197)
    at async /app/apps/viewer/.next/server/pages/api/[...trpc].js:1:21529
    at async resolveMiddleware (file:///app/node_modules/@trpc/server/dist/index.mjs:420:30)
    at async callRecursive (file:///app/node_modules/@trpc/server/dist/index.mjs:456:32)
    at async outputMiddleware (file:///app/node_modules/@trpc/server/dist/index.mjs:301:24)
    at async callRecursive (file:///app/node_modules/@trpc/server/dist/index.mjs:456:32)
    at async callRecursive (file:///app/node_modules/@trpc/server/dist/index.mjs:456:32)
    at async callRecursive (file:///app/node_modules/@trpc/server/dist/index.mjs:456:32)
    at async resolve (file:///app/node_modules/@trpc/server/dist/index.mjs:486:24)
    at async /app/apps/viewer/.next/server/pages/api/[...trpc].js:1:39127
```

so, what's wrong !!!
and how to investigate it and make it work again?

**Comment by piasonp2** [comment]
I am having the same exact problem. Hope you get replied soon so I can also rectify my issues too

**Comment by baptisteArno** [comment]
Thanks for the report! Fixing this now

**Comment by MotazHakim** [comment]
This edit made it work again 
thanks alot @baptisteArno

**Comment by henrygraff** [comment]
self-hosted typebot does not work on WhatsApp
