### ISSUE TITLE
Removing collaborator from flow results in 500 error

### ISSUE THREAD

**Issue by teq-dev** [baptisteArno/typebot.io#19]
We receive a 500 error in the browser, and the following error from the application when attempting to remove an existing collaborator from a flow. This only occurs for collaborators that have accepted the invitation to the flow and logged in. Pending collaborators who have not logged-in can be removed from the flow without issue.
```
builder_1  | PrismaClientKnownRequestError: 
builder_1  | Invalid `prisma.collaboratorsOnTypebots.delete()` invocation:
builder_1  | 
builder_1  | 
builder_1  |   An operation failed because it depends on one or more records that were required but not found. Record to delete does not exist.
builder_1  |     at Object.request (/app/node_modules/@prisma/client/runtime/index.js:39818:15)
builder_1  |     at async PrismaClient._request (/app/node_modules/@prisma/client/runtime/index.js:40649:18)
builder_1  |     at async handler (/app/.next/server/pages/api/typebots/[typebotId]/collaborators/[userId].js:80:9) {
builder_1  |   code: 'P2025',
builder_1  |   clientVersion: '3.11.1',
builder_1  |   meta: { cause: 'Record to delete does not exist.' }
builder_1  | }
```

**Comment by teq-dev** [comment]
I think this fixes it:

https://github.com/teq-dev/typebot.io/commit/a959d2077291a622e5153a4d01e73f6a4e99ae7b

**Comment by baptisteArno** [comment]
Thank you for the investigation 🔥
