### ISSUE TITLE
Self-hosted instance not initalising properly

### ISSUE THREAD

**Issue by arladmin** [baptisteArno/typebot.io#197]
Hi. I just set up the Docker version of the self-hosted config (on my local machine).
After bringing up the stack, i see this page when navigating to `192.168.1.242:8080`:
![image](https://user-images.githubusercontent.com/64059154/209372325-a9f2cfbf-d2f8-4010-bfbe-e09730edb9da.png)

Confused why i'm seeing this even though the SMTP config has been set properly.

Error message in the console:
```
[next-auth][error][CLIENT_FETCH_ERROR] 
2022-12-23 22:18:36 typebotio-typebot-builder-1  | https://next-auth.js.org/errors#client_fetch_error fetch failed {
2022-12-23 22:18:36 typebotio-typebot-builder-1  |   error: {
2022-12-23 22:18:36 typebotio-typebot-builder-1  |     message: 'fetch failed',
2022-12-23 22:18:36 typebotio-typebot-builder-1  |     stack: 'TypeError: fetch failed\n' +
2022-12-23 22:18:36 typebotio-typebot-builder-1  |       '    at Object.fetch (node:internal/deps/undici/undici:11118:11)\n' +
2022-12-23 22:18:36 typebotio-typebot-builder-1  |       '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)',
2022-12-23 22:18:36 typebotio-typebot-builder-1  |     name: 'TypeError'
2022-12-23 22:18:36 typebotio-typebot-builder-1  |   },
2022-12-23 22:18:36 typebotio-typebot-builder-1  |   url: 'http://192.168.1.242:8080/api/auth/session',
2022-12-23 22:18:36 typebotio-typebot-builder-1  |   message: 'fetch failed'
2022-12-23 22:18:36 typebotio-typebot-builder-1  | }
```

My `docker-compose.yml`:

```
version: '3.3'
services:
  typebot-db:
    image: postgres:13
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=typebot
      - POSTGRES_PASSWORD=typebot
    ports:
      - "1332:5432"
  typebot-builder:
    image: baptistearno/typebot-builder:latest
    restart: always
    depends_on:
      - typebot-db
    ports:
      - '8080:3000'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    # See https://docs.typebot.io/self-hosting/configuration for more configuration options
    environment:
      - DATABASE_URL=postgresql://postgres:typebot@typebot-db:5432/typebot
      - NEXTAUTH_URL=http://192.168.1.242:8080
      - NEXT_PUBLIC_VIEWER_URL=http://192.168.1.242:8081
      - ENCRYPTION_SECRET=<secret>
      - ADMIN_EMAIL=my-email
      - DISABLE_SIGNUP=true
      - SMTP_USERNAME=trybot@email
      - SMTP_PASSWORD=<password>
      - SMTP_HOST=<host>
      - SMTP_PORT=465
  typebot-viewer:
    image: baptistearno/typebot-viewer:latest
    restart: always
    ports:
      - '8081:3000'
    # See https://docs.typebot.io/self-hosting/configuration for more configuration options
    environment:
      - DATABASE_URL=postgresql://postgres:typebot@typebot-db:5432/typebot
      - NEXT_PUBLIC_VIEWER_URL=http://192.168.1.242:8081
      - ENCRYPTION_SECRET=<secret>
volumes:
  db_data:

```

Unable to bring the instance to a usable state so far.

**Comment by baptisteArno** [comment]
The builder container is trying to reach `http://192.168.1.242:8080` but the container can't resolve it. Only your hosting machine can.

For this to work, you could add the `NEXTAUTH_URL_INTERNAL` variable and set it to `http://localhost:3000`

**Comment by arladmin** [comment]
@baptisteArno Thanks for the prompt response.

Just implemented your suggestion, and don't see the fetch error anymore in the console.

But, i'm still stuck on the same login page. Can't register/Signin

**Comment by baptisteArno** [comment]
Check out: https://docs.typebot.io/self-hosting/configuration/builder#email-auth-notifications

You are missing `NEXT_PUBLIC_SMTP_FROM` 👍

**Comment by arladmin** [comment]
Indeed!

Moved one step ahead :) 

Now seeing this:
![image](https://user-images.githubusercontent.com/64059154/209375654-b5af600b-c4b7-4008-945c-82dfc9e30ae5.png)

**Comment by arladmin** [comment]
@baptisteArno 
I've set `DISABLE_SIGNUP=false` and then trying to create the user.

Still receiving the same error notification.
Also this error in the console:
```
[next-auth][error][SIGNIN_EMAIL_ERROR] 
2022-12-23 23:01:32 typebotio-typebot-builder-1  | https://next-auth.js.org/errors#signin_email_error Greeting never received {
2022-12-23 23:01:32 typebotio-typebot-builder-1  |   error: {
2022-12-23 23:01:32 typebotio-typebot-builder-1  |     message: 'Greeting never received',
2022-12-23 23:01:32 typebotio-typebot-builder-1  |     stack: 'Error: Greeting never received\n' +
2022-12-23 23:01:32 typebotio-typebot-builder-1  |       '    at SMTPConnection._formatError (/app/node_modules/.pnpm/nodemailer@6.8.0/node_modules/nodemailer/lib/smtp-connection/index.js:790:19)\n' +
2022-12-23 23:01:32 typebotio-typebot-builder-1  |       '    at SMTPConnection._onError (/app/node_modules/.pnpm/nodemailer@6.8.0/node_modules/nodemailer/lib/smtp-connection/index.js:776:20)\n' +
2022-12-23 23:01:32 typebotio-typebot-builder-1  |       '    at Timeout.<anonymous> (/app/node_modules/.pnpm/nodemailer@6.8.0/node_modules/nodemailer/lib/smtp-connection/index.js:710:22)\n' +
2022-12-23 23:01:32 typebotio-typebot-builder-1  |       '    at listOnTimeout (node:internal/timers:564:17)\n' +
2022-12-23 23:01:32 typebotio-typebot-builder-1  |       '    at process.processTimers (node:internal/timers:507:7)',
2022-12-23 23:01:32 typebotio-typebot-builder-1  |     name: 'Error'
2022-12-23 23:01:32 typebotio-typebot-builder-1  |   },
2022-12-23 23:01:32 typebotio-typebot-builder-1  |   providerId: 'email',
2022-12-23 23:01:32 typebotio-typebot-builder-1  |   message: 'Greeting never received'
2022-12-23 23:01:32 typebotio-typebot-builder-1  | }
```

**Comment by baptisteArno** [comment]
Can you please read the SMTP config thoroughly? https://docs.typebot.io/self-hosting/configuration/builder#email-auth-notifications

You need to set `SMTP_SECURE` to `true` if you are using port `465`

**Comment by arladmin** [comment]
@baptisteArno 
Getting this error after adding that:
```
2022-12-23 23:08:54 typebotio-typebot-builder-1  | [next-auth][error][SIGNIN_EMAIL_ERROR] 
2022-12-23 23:08:54 typebotio-typebot-builder-1  | https://next-auth.js.org/errors#signin_email_error Invalid login: 535 5.7.8 ab0d8b8f-82e8-11ed-b383-cde5ad41a1dd {
2022-12-23 23:08:54 typebotio-typebot-builder-1  |   error: {
2022-12-23 23:08:54 typebotio-typebot-builder-1  |     message: 'Invalid login: 535 5.7.8 ab0d8b8f-82e8-11ed-b383-cde5ad41a1dd',
2022-12-23 23:08:54 typebotio-typebot-builder-1  |     stack: 'Error: Invalid login: 535 5.7.8 ab0d8b8f-82e8-11ed-b383-cde5ad41a1dd\n' +
2022-12-23 23:08:54 typebotio-typebot-builder-1  |       '    at SMTPConnection._formatError (/app/node_modules/.pnpm/nodemailer@6.8.0/node_modules/nodemailer/lib/smtp-connection/index.js:790:19)\n' +
2022-12-23 23:08:54 typebotio-typebot-builder-1  |       '    at SMTPConnection._actionAUTHComplete (/app/node_modules/.pnpm/nodemailer@6.8.0/node_modules/nodemailer/lib/smtp-connection/index.js:1542:34)\n' +
2022-12-23 23:08:54 typebotio-typebot-builder-1  |       '    at SMTPConnection.<anonymous> (/app/node_modules/.pnpm/nodemailer@6.8.0/node_modules/nodemailer/lib/smtp-connection/index.js:546:26)\n' +
2022-12-23 23:08:54 typebotio-typebot-builder-1  |       '    at SMTPConnection._processResponse (/app/node_modules/.pnpm/nodemailer@6.8.0/node_modules/nodemailer/lib/smtp-connection/index.js:953:20)\n' +
2022-12-23 23:08:54 typebotio-typebot-builder-1  |       '    at SMTPConnection._onData (/app/node_modules/.pnpm/nodemailer@6.8.0/node_modules/nodemailer/lib/smtp-connection/index.js:755:14)\n' +
2022-12-23 23:08:54 typebotio-typebot-builder-1  |       '    at SMTPConnection._onSocketData (/app/node_modules/.pnpm/nodemailer@6.8.0/node_modules/nodemailer/lib/smtp-connection/index.js:193:44)\n' +
2022-12-23 23:08:54 typebotio-typebot-builder-1  |       '    at TLSSocket.emit (node:events:513:28)\n' +
2022-12-23 23:08:54 typebotio-typebot-builder-1  |       '    at TLSSocket.emit (node:domain:489:12)\n' +
2022-12-23 23:08:54 typebotio-typebot-builder-1  |       '    at addChunk (node:internal/streams/readable:324:12)\n' +
2022-12-23 23:08:54 typebotio-typebot-builder-1  |       '    at readableAddChunk (node:internal/streams/readable:297:9)',
2022-12-23 23:08:54 typebotio-typebot-builder-1  |     name: 'Error'
2022-12-23 23:08:54 typebotio-typebot-builder-1  |   },
2022-12-23 23:08:54 typebotio-typebot-builder-1  |   providerId: 'email',
2022-12-23 23:08:54 typebotio-typebot-builder-1  |   message: 'Invalid login: 535 5.7.8 ab0d8b8f-82e8-11ed-b383-cde5ad41a1dd'
2022-12-23 23:08:54 typebotio-typebot-builder-1  | }
```

**Comment by baptisteArno** [comment]
It means what it means, your SMTP login is not working. It has nothing to do with Typebot.

Make sure you enter valid SMTP config 👍

**Comment by arladmin** [comment]
@baptisteArno 

It's working now, but the issue wasn't with the SMTP.

It worked after i modified the email password and removed all special characters.

**Comment by baptisteArno** [comment]
Mmmmh good question, I might check this up then!

**Comment by viapratica** [comment]
Hello!

First of all congratulations for the project, I had the opportunity to meet him online. It's very good! But I've been trying in every way to put it to work on two of my servers, one on Linox with port 465 released and the other on Contabo, there's no way, it never sends the access confirmation email, I didn't try using a HostGator SMTP server and yesterday I tried using SMTP from Gmail. I made every possible combination. It always produces an error and when it is supposed to work, (I believe) it presents a password error in Gmail's SMTP.


`typebot-builder_1  | [next-auth][error][SIGNIN_EMAIL_ERROR]
typebot-builder_1  | https://next-auth.js.org/errors#signin_email_error Invalid login: 534-5.7.9 Application-specific password required. Learn more at
typebot-builder_1  | 534 5.7.9  https://support.google.com/mail/?p=InvalidSecondFactor j4-20020a05600c1c0400b003dc5b59ed7asm2701548wms.11 - gsmtp {
typebot-builder_1  |   error: {
typebot-builder_1  |     message: 'Invalid login: 534-5.7.9 Application-specific password required. Learn more at\n' +
typebot-builder_1  |       '534 5.7.9  https://support.google.com/mail/?p=InvalidSecondFactor j4-20020a05600c1c0400b003dc5b59ed7asm2701548wms.11 - gsmtp',
typebot-builder_1  |     stack: 'Error: Invalid login: 534-5.7.9 Application-specific password required. Learn more at\n' +
typebot-builder_1  |       '534 5.7.9  https://support.google.com/mail/?p=InvalidSecondFactor j4-20020a05600c1c0400b003dc5b59ed7asm2701548wms.11 - gsmtp\n' +
typebot-builder_1  |       '    at SMTPConnection._formatError (/app/node_modules/.pnpm/nodemailer@6.9.1/node_modules/nodemailer/lib/smtp-connection/index.js:790:19)\n' +
typebot-builder_1  |       '    at SMTPConnection._actionAUTHComplete (/app/node_modules/.pnpm/nodemailer@6.9.1/node_modules/nodemailer/lib/smtp-connection/index.js:1548:34)\n' +
typebot-builder_1  |       '    at SMTPConnection.<anonymous> (/app/node_modules/.pnpm/nodemailer@6.9.1/node_modules/nodemailer/lib/smtp-connection/index.js:546:26)\n' +
typebot-builder_1  |       '    at SMTPConnection._processResponse (/app/node_modules/.pnpm/nodemailer@6.9.1/node_modules/nodemailer/lib/smtp-connection/index.js:953:20)\n' +
typebot-builder_1  |       '    at SMTPConnection._onData (/app/node_modules/.pnpm/nodemailer@6.9.1/node_modules/nodemailer/lib/smtp-connection/index.js:755:14)\n' +
typebot-builder_1  |       '    at SMTPConnection._onSocketData (/app/node_modules/.pnpm/nodemailer@6.9.1/node_modules/nodemailer/lib/smtp-connection/index.js:193:44)\n' +
typebot-builder_1  |       '    at TLSSocket.emit (node:events:513:28)\n' +
typebot-builder_1  |       '    at TLSSocket.emit (node:domain:489:12)\n' +
typebot-builder_1  |       '    at addChunk (node:internal/streams/readable:324:12)\n' +
typebot-builder_1  |       '    at readableAddChunk (node:internal/streams/readable:297:9)',
typebot-builder_1  |     name: 'Error'
typebot-builder_1  |   },
typebot-builder_1  |   providerId: 'email',
typebot-builder_1  |   message: 'Invalid login: 534-5.7.9 Application-specific password required. Learn more at\n' +
typebot-builder_1  |     '534 5.7.9  https://support.google.com/mail/?p=InvalidSecondFactor j4-20020a05600c1c0400b003dc5b59ed7asm2701548wms.11 - gsmtp'
typebot-builder_1  | }`


docker-compose.yml


`version: '3.3'
services:
  typebot-db:
    image: postgres:13
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=typebot
      - POSTGRES_PASSWORD=typebot
  typebot-builder:
    image: baptistearno/typebot-builder:latest
    restart: always
    depends_on:
      - typebot-db
    ports:
      - '8080:3000'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    # See https://docs.typebot.io/self-hosting/configuration for more configuration options
#      - NEXT_PUBLIC_SMTP_FROM=Typebot
    environment:
      - DATABASE_URL=postgresql://postgres:typebot@typebot-db:5432/typebot
      - NEXTAUTH_URL=http://bot.***********.com.br:8080
      - NEXT_PUBLIC_VIEWER_URL=http://bot.***********.com.br:8081
      - ENCRYPTION_SECRET=cEpbI4XwmjkHIj5qFtTJWI***********
      - NEXTAUTH_URL_INTERNAL=http://localhost:3000
      - ADMIN_EMAIL=***********@gmail.com
      - SMTP_USERNAME=***********@gmail.com
      - SMTP_PASSWORD=***********
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=465
      - SMTP_SECURE=true
      - DISABLE_SIGNUP=false
      - NEXT_PUBLIC_SMTP_FROM=Typebot
         typebot-viewer:
    image: baptistearno/typebot-viewer:latest
    restart: always
    ports:
      - '8081:3000'
    # See https://docs.typebot.io/self-hosting/configuration for more configuration options
    environment:
      - DATABASE_URL=postgresql://postgres:typebot@typebot-db:5432/typebot
      - NEXT_PUBLIC_VIEWER_URL=http://bot.***********.com.br:8081
      - ENCRYPTION_SECRET=cEpbI4XwmjkHIj5qFtT***********
volumes:
  db_data:`

The Gmail and HostGator password does not have a special character, in some changes it says it was, it does not produce an error, but no e-mail arrives or anything is directed on the page.

I've tried docker, Manual and even Vercel.
My servers are Ubuntu 20

If anyone has a working docker-compose.yml with Gmail or HostGator and can share it, I appreciate it.

Thanks

**Comment by baptisteArno** [comment]
The error is pretty clear to me: "Application-specific password required."

See this: https://support.google.com/accounts/answer/185833?hl=en

**Comment by viapratica** [comment]
> The error is pretty clear to me: "Application-specific password required."
> 
> See this: https://support.google.com/accounts/answer/185833?hl=en



No, I'm not that new, I've been working with Linux servers since 1999, and I've installed thousands of systems, I provided the password according to the documentation, I also changed my password so it doesn't contain special characters, because I saw another user complaining, even so the system ignores it the SMTP_PASSWORD field, which has my Gmail password. The problem is not lack of Google account password.

Thanks for the answer

**Comment by baptisteArno** [comment]
If you are thinking it's an issue from Google then you need to send a support message to them as Typebot just waits for valid SMTP credentials, I can't do much here.

Also, I don't recommend at all to use your Gmail SMTP credentials. You could use services that are meant for this, for example: Mailgun, Sendinblue or Sendgrid.
