### ISSUE TITLE
Custom OAuth misses client ID and secret variables

### ISSUE THREAD

**Issue by Lanhild** [baptisteArno/typebot.io#216]
```bash
typebot-builder_1  | [next-auth][error][SIGNIN_OAUTH_ERROR] 
typebot-builder_1  | https://next-auth.js.org/errors#signin_oauth_error client_id is required {
typebot-builder_1  |   error: {
typebot-builder_1  |     message: 'client_id is required',
typebot-builder_1  |     stack: 'TypeError: client_id is required\n' +
typebot-builder_1  |       '    at new BaseClient (/app/node_modules/.pnpm/openid-client@5.3.1/node_modules/openid-client/lib/client.js:178:13)\n' +
typebot-builder_1  |       '    at new Client (/app/node_modules/.pnpm/openid-client@5.3.1/node_modules/openid-client/lib/client.js:1789:7)\n' +
typebot-builder_1  |       '    at openidClient (/app/node_modules/.pnpm/next-auth@4.18.7_mibeyvivfhhmvvbkd4wwrgzcom/node_modules/next-auth/core/lib/oauth/client.js:28:18)\n' +
typebot-builder_1  |       '    at getAuthorizationUrl (/app/node_modules/.pnpm/next-auth@4.18.7_mibeyvivfhhmvvbkd4wwrgzcom/node_modules/next-auth/core/lib/oauth/authorization-url.js:67:49)\n' +
typebot-builder_1  |       '    at Object.signin (/app/node_modules/.pnpm/next-auth@4.18.7_mibeyvivfhhmvvbkd4wwrgzcom/node_modules/next-auth/core/routes/signin.js:38:60)\n' +
typebot-builder_1  |       '    at AuthHandler (/app/node_modules/.pnpm/next-auth@4.18.7_mibeyvivfhhmvvbkd4wwrgzcom/node_modules/next-auth/core/index.js:253:39)\n' +
typebot-builder_1  |       '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
typebot-builder_1  |       '    at async NextAuthHandler (/app/node_modules/.pnpm/next-auth@4.18.7_mibeyvivfhhmvvbkd4wwrgzcom/node_modules/next-auth/next/index.js:23:19)',
typebot-builder_1  |     name: 'TypeError'
typebot-builder_1  |   },
typebot-builder_1  |   providerId: 'custom-oauth',
typebot-builder_1  |   message: 'client_id is required'
typebot-builder_1  | }
```

**Comment by baptisteArno** [comment]
Can you tell me what field I need to add to make it work? Client ID, Client Secret, anything else?

I'm not familiar with OAuth and I didn't know how to test this.

**Comment by Lanhild** [comment]
Client id and client secret should be the only fields you need to add
