### ISSUE TITLE
Custom OAuth callback URL doesn't work it uses the wrong method

### ISSUE THREAD

**Issue by Lanhild** [baptisteArno/typebot.io#224]
see logs
```bash
typebot-builder_1  | [next-auth][error][OAUTH_CALLBACK_ERROR] 
typebot-builder_1  | https://next-auth.js.org/errors#oauth_callback_error id_token detected in the response, you must use client.callback() instead of client.oauthCallback() {
typebot-builder_1  |   error: RPError: id_token detected in the response, you must use client.callback() instead of client.oauthCallback()
typebot-builder_1  |       at Client.oauthCallback (/app/node_modules/.pnpm/openid-client@5.3.1/node_modules/openid-client/lib/client.js:615:15)
typebot-builder_1  |       at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
typebot-builder_1  |       at async oAuthCallback (/app/node_modules/.pnpm/next-auth@4.18.7_mibeyvivfhhmvvbkd4wwrgzcom/node_modules/next-auth/core/lib/oauth/callback.js:129:16)
typebot-builder_1  |       at async Object.callback (/app/node_modules/.pnpm/next-auth@4.18.7_mibeyvivfhhmvvbkd4wwrgzcom/node_modules/next-auth/core/routes/callback.js:52:11)
typebot-builder_1  |       at async AuthHandler (/app/node_modules/.pnpm/next-auth@4.18.7_mibeyvivfhhmvvbkd4wwrgzcom/node_modules/next-auth/core/index.js:201:28)
typebot-builder_1  |       at async NextAuthHandler (/app/node_modules/.pnpm/next-auth@4.18.7_mibeyvivfhhmvvbkd4wwrgzcom/node_modules/next-auth/next/index.js:23:19) {
typebot-builder_1  |     name: 'OAuthCallbackError',
typebot-builder_1  |     code: undefined
typebot-builder_1  |   },
typebot-builder_1  |   providerId: 'custom-oauth',
typebot-builder_1  |   message: 'id_token detected in the response, you must use client.callback() instead of client.oauthCallback()'
typebot-builder_1  | }

```

**Comment by baptisteArno** [comment]
Setting the new `CUSTOM_OAUTH_ENABLE_ID_TOKEN` config to `true` should fix this error.
