### ISSUE TITLE
Stripe Unexpected token 'I', "Internal S"... is not valid JSON

### ISSUE THREAD

**Issue by valensto** [baptisteArno/typebot.io#272]
Hi, 

I'm trying to add stripe to Typebot and got this error:
`Unexpected token 'I', "Internal S"... is not valid JSON`

Test and Live key are tested with other tools and working I just got an error alert message in the frontend and got a 500 from the backend

The logs of builder container:

```
2023-01-24T21:06:53.705101754Z RangeError: Invalid key length
2023-01-24T21:06:53.705153915Z at Cipheriv.createCipherBase (node:internal/crypto/cipher:116:19)
2023-01-24T21:06:53.705161548Z at Cipheriv.createCipherWithIV (node:internal/crypto/cipher:135:3)
2023-01-24T21:06:53.705167865Z at new Cipheriv (node:internal/crypto/cipher:243:3)
2023-01-24T21:06:53.705173941Z at createCipheriv (node:crypto:141:10)
2023-01-24T21:06:53.705179895Z at encrypt (/app/apps/builder/.next/server/chunks/8185.js:95:55)
2023-01-24T21:06:53.705185896Z at handler (/app/apps/builder/.next/server/pages/api/credentials.js:86:101)
2023-01-24T21:06:53.705192091Z at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-01-24T21:06:53.705198049Z at async Object.apiResolver (/app/node_modules/.pnpm/next@13.1.2_pjwopsidmaokadturxaafygjp4/node_modules/next/dist/server/api-utils/node.js:363:9)
2023-01-24T21:06:53.705218737Z at async NextNodeServer.runApi (/app/node_modules/.pnpm/next@13.1.2_pjwopsidmaokadturxaafygjp4/node_modules/next/dist/server/next-server.js:488:9)
2023-01-24T21:06:53.705224994Z at async Object.fn (/app/node_modules/.pnpm/next@13.1.2_pjwopsidmaokadturxaafygjp4/node_modules/next/dist/server/next-server.js:750:37) {
2023-01-24T21:06:53.705230638Z code: 'ERR_CRYPTO_INVALID_KEYLEN'
2023-01-24T21:06:53.705235771Z }
```

I use the latest version of docker image on debian 11 with latest version of docker install on it.

Thanks :)

**Comment by baptisteArno** [comment]
You might have generated an invalid `ENCRYPTION_SECRET`?

Can you add a new one? You can generate it with this command:

```sh
openssl rand -base64 24 | tr -d '\n' ; echo
```

**Comment by valensto** [comment]
@baptisteArno yes it's ok thank I installed it with caprover fresh install and got a secret of 128 char that I don't check it up ...

Thanks for the tool I discovered it yesterday with my students!
