### ISSUE TITLE
Trying to login with Custom OAuth renders in an error

### ISSUE THREAD

**Issue by Lanhild** [baptisteArno/typebot.io#279]
```bash
typebot-builder_1  | Invalid `prisma.memberInWorkspace.createMany()` invocation:
typebot-builder_1  | 
typebot-builder_1  | 
typebot-builder_1  | Unique constraint failed on the fields: (`userId`,`workspaceId`)
typebot-builder_1  | [next-auth][error][adapter_error_createUser] 
typebot-builder_1  | https://next-auth.js.org/errors#adapter_error_createuser 
typebot-builder_1  | Invalid `prisma.memberInWorkspace.createMany()` invocation:
typebot-builder_1  | 
typebot-builder_1  | 
typebot-builder_1  | Unique constraint failed on the fields: (`userId`,`workspaceId`) {
typebot-builder_1  |   message: '\n' +
typebot-builder_1  |     'Invalid `prisma.memberInWorkspace.createMany()` invocation:\n' +
typebot-builder_1  |     '\n' +
typebot-builder_1  |     '\n' +
typebot-builder_1  |     'Unique constraint failed on the fields: (`userId`,`workspaceId`)',
typebot-builder_1  |   stack: 'Error: \n' +
typebot-builder_1  |     'Invalid `prisma.memberInWorkspace.createMany()` invocation:\n' +
typebot-builder_1  |     '\n' +
typebot-builder_1  |     '\n' +
typebot-builder_1  |     'Unique constraint failed on the fields: (`userId`,`workspaceId`)\n' +
typebot-builder_1  |     '    at RequestHandler.handleRequestError (/app/node_modules/.pnpm/@prisma+client@4.8.1_prisma@4.8.1/node_modules/@prisma/client/runtime/index.js:35024:13)\n' +
typebot-builder_1  |     '    at RequestHandler.handleAndLogRequestError (/app/node_modules/.pnpm/@prisma+client@4.8.1_prisma@4.8.1/node_modules/@prisma/client/runtime/index.js:34996:12)\n' +
typebot-builder_1  |     '    at RequestHandler.request (/app/node_modules/.pnpm/@prisma+client@4.8.1_prisma@4.8.1/node_modules/@prisma/client/runtime/index.js:34991:12)\n' +
typebot-builder_1  |     '    at async PrismaClient._request (/app/node_modules/.pnpm/@prisma+client@4.8.1_prisma@4.8.1/node_modules/@prisma/client/runtime/index.js:36082:16)\n' +
typebot-builder_1  |     '    at async joinWorkspaces (/app/apps/builder/.next/server/chunks/7701.js:125:5)\n' +
typebot-builder_1  |     '    at async createUser (/app/apps/builder/.next/server/chunks/3794.js:69:50)',
typebot-builder_1  |   name: 'Error'
typebot-builder_1  | }
typebot-builder_1  | prisma:error 
```
Even when using a different email/email that has never been used in the Typebot instance, I get this error when I try to login using a custom OAuth provider

**Comment by baptisteArno** [comment]
Did you succeed to log in with your custom OAuth provider once before?

Can you check your database table "WorkspaceInvitation" do you have anything in it?

**Comment by Lanhild** [comment]
I do have entries inside `WorkspaceInvitation`, and no, I couldn't login with my OAuth provider before
