### ISSUE TITLE
The bot you're looking for doesn't exist

### ISSUE THREAD

**Issue by b4oshany** [baptisteArno/typebot.io#292]
package.json file in the typebot_viewer container
```json
{
  "version": "2.10.0",
  "name": "typebot-os",
  "private": true,
  "license": "AGPL-3.0-or-later",
  "workspaces": [
    "packages/*",
    "apps/*"
  ],
}
```

Docker Log:
```
env.sh loaded
Matched inline env:
NEXT_PUBLIC_VIEWER_URL=bots.****.com
Reading ./apps/viewer/.env.production...
NEXT_PUBLIC_VIEWER_URL=
NEXT_PUBLIC_E2E_TEST=
NEXT_PUBLIC_VIEWER_URL=bots.****.com
Got index from inline env: 0, replacing NEXT_PUBLIC_VIEWER_URL
env.sh done

Prisma schema loaded from prisma/schema.prisma

✔ Generated Prisma Client (4.9.0 | library) to ./node_modules/.pnpm/@prisma+client@4.9.0_prisma@4.9.0/node_modules/@prisma/client in 411ms
You can now start using Prisma Client in your code. Reference: https://pris.ly/d/client
```
import { PrismaClient } from '@prisma/client'
const prisma = new PrismaClient()
```
info  - Loaded env from /app/apps/viewer/.env.production
Listening on port 3000 url: http://9c8fdb6ac216:3000
TypeError: Cannot read properties of undefined (reading 'split')
    at /app/apps/viewer/.next/server/pages/[[...publicId]].js:296:160
    at Array.some (<anonymous>)
    at getServerSideProps (/app/apps/viewer/.next/server/pages/[[...publicId]].js:296:102)
    at Object.renderToHTML (/app/node_modules/.pnpm/next@13.1.6_pjwopsidmaokadturxaafygjp4/node_modules/next/dist/server/render.js:507:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async doRender (/app/node_modules/.pnpm/next@13.1.6_pjwopsidmaokadturxaafygjp4/node_modules/next/dist/server/base-server.js:720:34)
    at async cacheEntry.responseCache.get.incrementalCache.incrementalCache (/app/node_modules/.pnpm/next@13.1.6_pjwopsidmaokadturxaafygjp4/node_modules/next/dist/server/base-server.js:837:28)
    at async /app/node_modules/.pnpm/next@13.1.6_pjwopsidmaokadturxaafygjp4/node_modules/next/dist/server/response-cache/index.js:83:36
TypeError: Cannot read properties of undefined (reading 'split')
    at /app/apps/viewer/.next/server/pages/[[...publicId]].js:296:160
    at Array.some (<anonymous>)
    at getServerSideProps (/app/apps/viewer/.next/server/pages/[[...publicId]].js:296:102)
    at Object.renderToHTML (/app/node_modules/.pnpm/next@13.1.6_pjwopsidmaokadturxaafygjp4/node_modules/next/dist/server/render.js:507:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async doRender (/app/node_modules/.pnpm/next@13.1.6_pjwopsidmaokadturxaafygjp4/node_modules/next/dist/server/base-server.js:720:34)
    at async cacheEntry.responseCache.get.incrementalCache.incrementalCache (/app/node_modules/.pnpm/next@13.1.6_pjwopsidmaokadturxaafygjp4/node_modules/next/dist/server/base-server.js:837:28)
    at async /app/node_modules/.pnpm/next@13.1.6_pjwopsidmaokadturxaafygjp4/node_modules/next/dist/server/response-cache/index.js:83:36
TypeError: Cannot read properties of undefined (reading 'split')
    at /app/apps/viewer/.next/server/pages/[[...publicId]].js:296:160
    at Array.some (<anonymous>)
    at getServerSideProps (/app/apps/viewer/.next/server/pages/[[...publicId]].js:296:102)
    at Object.renderToHTML (/app/node_modules/.pnpm/next@13.1.6_pjwopsidmaokadturxaafygjp4/node_modules/next/dist/server/render.js:507:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async doRender (/app/node_modules/.pnpm/next@13.1.6_pjwopsidmaokadturxaafygjp4/node_modules/next/dist/server/base-server.js:720:34)
    at async cacheEntry.responseCache.get.incrementalCache.incrementalCache (/app/node_modules/.pnpm/next@13.1.6_pjwopsidmaokadturxaafygjp4/node_modules/next/dist/server/base-server.js:837:28)
    at async /app/node_modules/.pnpm/next@13.1.6_pjwopsidmaokadturxaafygjp4/node_modules/next/dist/server/response-cache/index.js:83:36
```

**Comment by baptisteArno** [comment]
It looks like`NEXT_PUBLIC_VIEWER_URL` in the viewer container env. Are you sure you configured it on both builder and viewer?

**Comment by b4oshany** [comment]
I resolved it. Apparently, portainer wasn't loading the docker secrets in the container properly
