### ISSUE TITLE
Latest build - Error importing typbot json files created pre-v2.1.0

### ISSUE THREAD

**Issue by teq-dev** [baptisteArno/typebot.io#43]
Are we able to create new Typebots in the latest build by importing typebot json files that were exported from v.2.0? I am trying and receiving an error. Is this because the concept of ownerIds is gone?

```
builder_1  | PrismaClientValidationError: Unknown arg `ownerId` in data.ownerId for type TypebotUncheckedCreateInput. Did you mean `folderId`?
builder_1  |
builder_1  |     at Object.validate (/app/node_modules/@prisma/client/runtime/index.js:44201:20)
builder_1  |     at PrismaClient._executeRequest (/app/node_modules/@prisma/client/runtime/index.js:46354:17)
builder_1  |     at consumer (/app/node_modules/@prisma/client/runtime/index.js:46298:23)
builder_1  |     at /app/node_modules/@prisma/client/runtime/index.js:46302:76
builder_1  |     at runInChildSpan (/app/node_modules/@prisma/client/runtime/index.js:45510:12)
builder_1  |     at /app/node_modules/@prisma/client/runtime/index.js:46302:20
builder_1  |     at AsyncResource.runInAsyncScope (node:async_hooks:202:9)
builder_1  |     at PrismaClient._request (/app/node_modules/@prisma/client/runtime/index.js:46301:86)
builder_1  |     at /app/node_modules/@prisma/client/runtime/index.js:42862:25
builder_1  |     at _callback (/app/node_modules/@prisma/client/runtime/index.js:42626:52) {
builder_1  |   clientVersion: '3.14.0'
builder_1  | }
```

**Comment by baptisteArno** [comment]
Indeed, you need to remove the line that starts with "ownerId" in your JSON files, then it should be importable :)
