### ISSUE TITLE
Manual Build: Builder Build Errors

### ISSUE THREAD

**Issue by itzomen** [baptisteArno/typebot.io#489]
I use manual deployment and I have been trying to deploy the recent updates but I'm not able to build the builder app

## Building with `pnpm buid:builder`
```bash
> typebot-os@2.13.0 build:builder /home/omen/Traleor/typebot.io
> turbo run build --filter=builder... && turbo run build:env --filter=builder...

 WARNING  failed to contact turbod. Continuing in standalone mode: connection to turbo daemon process failed. Please ensure the following:
	- the process identified by the pid in the file at /tmp/turbod/d6399d38a3b8abe1/turbod.pid is not running, and remove /tmp/turbod/d6399d38a3b8abe1/turbod.pid
	- check the logs at /home/omen/.local/share/turborepo/logs/d6399d38a3b8abe1-typebot.io.log
	- the unix domain socket at /tmp/turbod/d6399d38a3b8abe1/turbod.sock has been removed
	You can also run without the daemon process by passing --no-daemon
• Packages in scope: @typebot.io/emails, @typebot.io/js, @typebot.io/lib, @typebot.io/prisma, @typebot.io/react, @typebot.io/schemas, @typebot.io/tsconfig, builder, eslint-config-custom
• Running build in 9 packages
• Remote caching disabled
@typebot.io/prisma:db:generate: cache bypass, force executing 1bf3ddd5147db38a
@typebot.io/prisma:db:generate: 
@typebot.io/prisma:db:generate: > @typebot.io/prisma@0.1.0 db:generate /home/omen/Traleor/typebot.io/packages/prisma
@typebot.io/prisma:db:generate: > tsx scripts/db-generate.ts
@typebot.io/prisma:db:generate: 
@typebot.io/prisma:db:generate: Executing for PostgreSQL schema
@typebot.io/prisma:db:generate: Environment variables loaded from .env
@typebot.io/prisma:db:generate: Prisma schema loaded from postgresql/schema.prisma
@typebot.io/prisma:db:generate: 
@typebot.io/prisma:db:generate: ✔ Generated Prisma Client (4.13.0 | library) to ./../../node_modules/.pnpm/@prisma+client@4.13.0_prisma@4.13.0/node_modules/@prisma/client in 981ms
@typebot.io/prisma:db:generate: You can now start using Prisma Client in your code. Reference: https://pris.ly/d/client
@typebot.io/prisma:db:generate: ```
@typebot.io/prisma:db:generate: import { PrismaClient } from '@prisma/client'
@typebot.io/prisma:db:generate: const prisma = new PrismaClient()
@typebot.io/prisma:db:generate: ```
@typebot.io/prisma:db:generate: 
@typebot.io/js:build: cache hit, suppressing output a349e7d9dac81f9c
@typebot.io/react:build: cache hit, suppressing output 5ffdaf4783d4d886
builder:build: cache miss, executing 2e6f7e93fe1009da
builder:build: 
builder:build: > builder@0.1.0 build /home/omen/Traleor/typebot.io/apps/builder
builder:build: > cross-env ENVSH_ENV=.env.local bash ../../scripts/env.sh next build
builder:build: 
builder:build: env.sh loaded
builder:build: Matched inline env:
builder:build: Reading .env.local...
builder:build: NEXT_PUBLIC_VIEWER_URL=https://bot.company.com
builder:build: NEXT_PUBLIC_VIEWER_INTERNAL_URL=https://bot.company.com
builder:build: NEXT_PUBLIC_GIPHY_API_KEY=key
builder:build: NEXT_PUBLIC_SMTP_FROM=Notifications <notifications@company.com>
builder:build: env.sh done
builder:build: 
builder:build: info  - Loaded env from /home/omen/Traleor/typebot.io/apps/builder/.env.local
builder:build: warn  - You have enabled experimental feature (outputFileTracingRoot) in next.config.js.
builder:build: warn  - Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use at your own risk.
builder:build: 
builder:build: info  - Linting and checking validity of types...
builder:build: info  - Creating an optimized production build...
builder:build: warn  - Compiled with warnings
builder:build: 
builder:build: ../../node_modules/.pnpm/mjml-core@4.14.1/node_modules/mjml-core/lib/helpers/mjmlconfig.js
builder:build: Critical dependency: the request of a dependency is an expression
builder:build: 
builder:build: Import trace for requested module:
builder:build: ../../node_modules/.pnpm/mjml-core@4.14.1/node_modules/mjml-core/lib/helpers/mjmlconfig.js
builder:build: ../../node_modules/.pnpm/mjml-core@4.14.1/node_modules/mjml-core/lib/index.js
builder:build: ../../node_modules/.pnpm/mjml@4.14.1/node_modules/mjml/lib/index.js
builder:build: ../../node_modules/.pnpm/@faire+mjml-react@3.2.0_react@18.2.0/node_modules/@faire/mjml-react/utils/render.js
builder:build: ../../packages/emails/src/emails/AlmostReachedChatsLimitEmail.tsx
builder:build: ../../packages/emails/src/emails/index.ts
builder:build: ../../packages/emails/src/index.ts
builder:build: ./src/features/auth/helpers/sendVerificationRequest.ts
builder:build: ./src/pages/api/auth/[...nextauth].ts
builder:build: 
builder:build: ../../node_modules/.pnpm/mjml-core@4.14.1/node_modules/mjml-core/lib/helpers/mjmlconfig.js
builder:build: Critical dependency: the request of a dependency is an expression
builder:build: 
builder:build: Import trace for requested module:
builder:build: ../../node_modules/.pnpm/mjml-core@4.14.1/node_modules/mjml-core/lib/helpers/mjmlconfig.js
builder:build: ../../node_modules/.pnpm/mjml-core@4.14.1/node_modules/mjml-core/lib/index.js
builder:build: ../../node_modules/.pnpm/mjml@4.14.1/node_modules/mjml/lib/index.js
builder:build: ../../node_modules/.pnpm/@faire+mjml-react@3.2.0_react@18.2.0/node_modules/@faire/mjml-react/utils/render.js
builder:build: ../../packages/emails/src/emails/AlmostReachedChatsLimitEmail.tsx
builder:build: ../../packages/emails/src/emails/index.ts
builder:build: ../../packages/emails/src/index.ts
builder:build: ./src/features/auth/helpers/sendVerificationRequest.ts
builder:build: ./src/pages/api/auth/[...nextauth].ts
builder:build: 
builder:build: ../../node_modules/.pnpm/mjml-core@4.14.1/node_modules/mjml-core/lib/helpers/mjmlconfig.js
builder:build: Critical dependency: the request of a dependency is an expression
builder:build: 
builder:build: Import trace for requested module:
builder:build: ../../node_modules/.pnpm/mjml-core@4.14.1/node_modules/mjml-core/lib/helpers/mjmlconfig.js
builder:build: ../../node_modules/.pnpm/mjml-core@4.14.1/node_modules/mjml-core/lib/index.js
builder:build: ../../node_modules/.pnpm/mjml@4.14.1/node_modules/mjml/lib/index.js
builder:build: ../../node_modules/.pnpm/@faire+mjml-react@3.2.0_react@18.2.0/node_modules/@faire/mjml-react/utils/render.js
builder:build: ../../packages/emails/src/emails/AlmostReachedChatsLimitEmail.tsx
builder:build: ../../packages/emails/src/emails/index.ts
builder:build: ../../packages/emails/src/index.ts
builder:build: ./src/features/auth/helpers/sendVerificationRequest.ts
builder:build: ./src/pages/api/auth/[...nextauth].ts
builder:build: 
builder:build: ../../node_modules/.pnpm/mjml-core@4.14.1/node_modules/mjml-core/lib/helpers/mjmlconfig.js
builder:build: Critical dependency: the request of a dependency is an expression
builder:build: 
builder:build: Import trace for requested module:
builder:build: ../../node_modules/.pnpm/mjml-core@4.14.1/node_modules/mjml-core/lib/helpers/mjmlconfig.js
builder:build: ../../node_modules/.pnpm/mjml-core@4.14.1/node_modules/mjml-core/lib/index.js
builder:build: ../../node_modules/.pnpm/mjml@4.14.1/node_modules/mjml/lib/index.js
builder:build: ../../node_modules/.pnpm/@faire+mjml-react@3.2.0_react@18.2.0/node_modules/@faire/mjml-react/utils/render.js
builder:build: ../../packages/emails/src/emails/AlmostReachedChatsLimitEmail.tsx
builder:build: ../../packages/emails/src/emails/index.ts
builder:build: ../../packages/emails/src/index.ts
builder:build: ./src/features/auth/helpers/sendVerificationRequest.ts
builder:build: ./src/pages/api/auth/[...nextauth].ts
builder:build: 
builder:build: ../../node_modules/.pnpm/mjml-core@4.14.1/node_modules/mjml-core/lib/index.js
builder:build: Critical dependency: the request of a dependency is an expression
builder:build: 
builder:build: Import trace for requested module:
builder:build: ../../node_modules/.pnpm/mjml-core@4.14.1/node_modules/mjml-core/lib/index.js
builder:build: ../../node_modules/.pnpm/mjml@4.14.1/node_modules/mjml/lib/index.js
builder:build: ../../node_modules/.pnpm/@faire+mjml-react@3.2.0_react@18.2.0/node_modules/@faire/mjml-react/utils/render.js
builder:build: ../../packages/emails/src/emails/AlmostReachedChatsLimitEmail.tsx
builder:build: ../../packages/emails/src/emails/index.ts
builder:build: ../../packages/emails/src/index.ts
builder:build: ./src/features/auth/helpers/sendVerificationRequest.ts
builder:build: ./src/pages/api/auth/[...nextauth].ts
builder:build: 
builder:build: ../../node_modules/.pnpm/node-fetch@2.6.9/node_modules/node-fetch/lib/index.js
builder:build: Module not found: Can't resolve 'encoding' in '/home/omen/Traleor/typebot.io/node_modules/.pnpm/node-fetch@2.6.9/node_modules/node-fetch/lib'
builder:build: 
builder:build: Import trace for requested module:
builder:build: ../../node_modules/.pnpm/node-fetch@2.6.9/node_modules/node-fetch/lib/index.js
builder:build: ../../node_modules/.pnpm/web-resource-inliner@6.0.1/node_modules/web-resource-inliner/src/util.js
builder:build: ../../node_modules/.pnpm/web-resource-inliner@6.0.1/node_modules/web-resource-inliner/src/html.js
builder:build: ../../node_modules/.pnpm/web-resource-inliner@6.0.1/node_modules/web-resource-inliner/src/inline.js
builder:build: ../../node_modules/.pnpm/juice@9.0.0/node_modules/juice/index.js
builder:build: ../../node_modules/.pnpm/mjml-core@4.14.1/node_modules/mjml-core/lib/index.js
builder:build: ../../node_modules/.pnpm/mjml@4.14.1/node_modules/mjml/lib/index.js
builder:build: ../../node_modules/.pnpm/@faire+mjml-react@3.2.0_react@18.2.0/node_modules/@faire/mjml-react/utils/render.js
builder:build: ../../packages/emails/src/emails/AlmostReachedChatsLimitEmail.tsx
builder:build: ../../packages/emails/src/emails/index.ts
builder:build: ../../packages/emails/src/index.ts
builder:build: ./src/features/auth/helpers/sendVerificationRequest.ts
builder:build: ./src/pages/api/auth/[...nextauth].ts
builder:build: 
builder:build: ../../node_modules/.pnpm/mjml-core@4.14.1/node_modules/mjml-core/lib/helpers/mjmlconfig.js
builder:build: Critical dependency: the request of a dependency is an expression
builder:build: 
builder:build: Import trace for requested module:
builder:build: ../../node_modules/.pnpm/mjml-core@4.14.1/node_modules/mjml-core/lib/helpers/mjmlconfig.js
builder:build: ../../node_modules/.pnpm/mjml-core@4.14.1/node_modules/mjml-core/lib/index.js
builder:build: ../../node_modules/.pnpm/mjml@4.14.1/node_modules/mjml/lib/index.js
builder:build: ../../node_modules/.pnpm/@faire+mjml-react@3.2.0_react@18.2.0/node_modules/@faire/mjml-react/utils/render.js
builder:build: ../../packages/emails/src/emails/AlmostReachedChatsLimitEmail.tsx
builder:build: ../../packages/emails/src/emails/index.ts
builder:build: ../../packages/emails/src/index.ts
builder:build: 
builder:build: ../../node_modules/.pnpm/mjml-core@4.14.1/node_modules/mjml-core/lib/helpers/mjmlconfig.js
builder:build: Critical dependency: the request of a dependency is an expression
builder:build: 
builder:build: Import trace for requested module:
builder:build: ../../node_modules/.pnpm/mjml-core@4.14.1/node_modules/mjml-core/lib/helpers/mjmlconfig.js
builder:build: ../../node_modules/.pnpm/mjml-core@4.14.1/node_modules/mjml-core/lib/index.js
builder:build: ../../node_modules/.pnpm/mjml@4.14.1/node_modules/mjml/lib/index.js
builder:build: ../../node_modules/.pnpm/@faire+mjml-react@3.2.0_react@18.2.0/node_modules/@faire/mjml-react/utils/render.js
builder:build: ../../packages/emails/src/emails/AlmostReachedChatsLimitEmail.tsx
builder:build: ../../packages/emails/src/emails/index.ts
builder:build: ../../packages/emails/src/index.ts
builder:build: 
builder:build: ../../node_modules/.pnpm/mjml-core@4.14.1/node_modules/mjml-core/lib/helpers/mjmlconfig.js
builder:build: Critical dependency: the request of a dependency is an expression
builder:build: 
builder:build: Import trace for requested module:
builder:build: ../../node_modules/.pnpm/mjml-core@4.14.1/node_modules/mjml-core/lib/helpers/mjmlconfig.js
builder:build: ../../node_modules/.pnpm/mjml-core@4.14.1/node_modules/mjml-core/lib/index.js
builder:build: ../../node_modules/.pnpm/mjml@4.14.1/node_modules/mjml/lib/index.js
builder:build: ../../node_modules/.pnpm/@faire+mjml-react@3.2.0_react@18.2.0/node_modules/@faire/mjml-react/utils/render.js
builder:build: ../../packages/emails/src/emails/AlmostReachedChatsLimitEmail.tsx
builder:build: ../../packages/emails/src/emails/index.ts
builder:build: ../../packages/emails/src/index.ts
builder:build: 
builder:build: ../../node_modules/.pnpm/mjml-core@4.14.1/node_modules/mjml-core/lib/helpers/mjmlconfig.js
builder:build: Critical dependency: the request of a dependency is an expression
builder:build: 
builder:build: Import trace for requested module:
builder:build: ../../node_modules/.pnpm/mjml-core@4.14.1/node_modules/mjml-core/lib/helpers/mjmlconfig.js
builder:build: ../../node_modules/.pnpm/mjml-core@4.14.1/node_modules/mjml-core/lib/index.js
builder:build: ../../node_modules/.pnpm/mjml@4.14.1/node_modules/mjml/lib/index.js
builder:build: ../../node_modules/.pnpm/@faire+mjml-react@3.2.0_react@18.2.0/node_modules/@faire/mjml-react/utils/render.js
builder:build: ../../packages/emails/src/emails/AlmostReachedChatsLimitEmail.tsx
builder:build: ../../packages/emails/src/emails/index.ts
builder:build: ../../packages/emails/src/index.ts
builder:build: 
builder:build: ../../node_modules/.pnpm/mjml-core@4.14.1/node_modules/mjml-core/lib/index.js
builder:build: Critical dependency: the request of a dependency is an expression
builder:build: 
builder:build: info  - Collecting page data...
builder:build: Import trace for requested module:
builder:build: ../../node_modules/.pnpm/mjml-core@4.14.1/node_modules/mjml-core/lib/index.js
builder:build: ../../node_modules/.pnpm/mjml@4.14.1/node_modules/mjml/lib/index.js
builder:build: ../../node_modules/.pnpm/@faire+mjml-react@3.2.0_react@18.2.0/node_modules/@faire/mjml-react/utils/render.js
builder:build: ../../packages/emails/src/emails/AlmostReachedChatsLimitEmail.tsx
builder:build: ../../packages/emails/src/emails/index.ts
builder:build: ../../packages/emails/src/index.ts
builder:build: 
builder:build: ../../node_modules/.pnpm/node-fetch@2.6.9/node_modules/node-fetch/lib/index.js
builder:build: Module not found: Can't resolve 'encoding' in '/home/omen/Traleor/typebot.io/node_modules/.pnpm/node-fetch@2.6.9/node_modules/node-fetch/lib'
builder:build: 
builder:build: Import trace for requested module:
builder:build: ../../node_modules/.pnpm/node-fetch@2.6.9/node_modules/node-fetch/lib/index.js
builder:build: ../../node_modules/.pnpm/web-resource-inliner@6.0.1/node_modules/web-resource-inliner/src/util.js
builder:build: ../../node_modules/.pnpm/web-resource-inliner@6.0.1/node_modules/web-resource-inliner/src/html.js
builder:build: ../../node_modules/.pnpm/web-resource-inliner@6.0.1/node_modules/web-resource-inliner/src/inline.js
builder:build: ../../node_modules/.pnpm/juice@9.0.0/node_modules/juice/index.js
builder:build: ../../node_modules/.pnpm/mjml-core@4.14.1/node_modules/mjml-core/lib/index.js
builder:build: ../../node_modules/.pnpm/mjml@4.14.1/node_modules/mjml/lib/index.js
builder:build: ../../node_modules/.pnpm/@faire+mjml-react@3.2.0_react@18.2.0/node_modules/@faire/mjml-react/utils/render.js
builder:build: ../../packages/emails/src/emails/AlmostReachedChatsLimitEmail.tsx
builder:build: ../../packages/emails/src/emails/index.ts
builder:build: ../../packages/emails/src/index.ts
builder:build: 
builder:build: TypeError: Cannot read properties of undefined (reading '1')
builder:build:     at isFileType (node:fs:218:19)
builder:build:     at Object.readFileSync (node:fs:472:16)
builder:build:     at /home/omen/Traleor/typebot.io/apps/builder/.next/server/chunks/8979.js:92552:19
builder:build:     at Array.map (<anonymous>)
builder:build:     at /home/omen/Traleor/typebot.io/apps/builder/.next/server/chunks/8979.js:92551:30
builder:build:     at 798 (/home/omen/Traleor/typebot.io/apps/builder/.next/server/chunks/8979.js:92556:2)
builder:build:     at __webpack_require__ (/home/omen/Traleor/typebot.io/apps/builder/.next/server/webpack-runtime.js:25:43)
builder:build:     at 4453 (/home/omen/Traleor/typebot.io/apps/builder/.next/server/chunks/8979.js:25748:16)
builder:build:     at __webpack_require__ (/home/omen/Traleor/typebot.io/apps/builder/.next/server/webpack-runtime.js:25:43)
builder:build:     at 4162 (/home/omen/Traleor/typebot.io/apps/builder/.next/server/chunks/8979.js:1511:25)
builder:build: 
builder:build: > Build error occurred
builder:build: Error: Failed to collect page data for /
builder:build:     at /home/omen/Traleor/typebot.io/node_modules/.pnpm/next@13.3.4_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/build/utils.js:1152:15
builder:build:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
builder:build:   type: 'Error'
builder:build: }
builder:build:  ELIFECYCLE  Command failed with exit code 1.
builder:build: ERROR: command finished with error: command (/home/omen/Traleor/typebot.io/apps/builder) pnpm run build exited (1)
command (/home/omen/Traleor/typebot.io/apps/builder) pnpm run build exited (1)

 Tasks:    3 successful, 4 total
Cached:    2 cached, 4 total
  Time:    2m49.059s 

 ERROR  run failed: command  exited (1)
 ELIFECYCLE  Command failed with exit code 1.

```

## Building with `pnpm buid` in apps/builder folder
```bash
> builder@0.1.0 build /home/omen/Traleor/typebot.io/apps/builder
> cross-env ENVSH_ENV=.env.local bash ../../scripts/env.sh next build

env.sh loaded
Matched inline env:
Reading .env.local...
NEXT_PUBLIC_VIEWER_URL=https://bot.company.com
NEXT_PUBLIC_VIEWER_INTERNAL_URL=https://bot.company.com
NEXT_PUBLIC_GIPHY_API_KEY=key
NEXT_PUBLIC_SMTP_FROM=Notifications <notifications@company.com>
env.sh done

info  - Loaded env from /home/omen/Traleor/typebot.io/apps/builder/.env.local
warn  - You have enabled experimental feature (outputFileTracingRoot) in next.config.js.
warn  - Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use at your own risk.

info  - Linting and checking validity of types  
Warning: For production Image Optimization with Next.js, the optional 'sharp' package is strongly recommended. Run 'yarn add sharp', and Next.js will use it automatically for Image Optimization.
Read more: https://nextjs.org/docs/messages/sharp-missing-in-production
warn  - Compiled with warnings

../../node_modules/.pnpm/mjml-core@4.14.1/node_modules/mjml-core/lib/helpers/mjmlconfig.js
Critical dependency: the request of a dependency is an expression

Import trace for requested module:
../../node_modules/.pnpm/mjml-core@4.14.1/node_modules/mjml-core/lib/helpers/mjmlconfig.js
../../node_modules/.pnpm/mjml-core@4.14.1/node_modules/mjml-core/lib/index.js
../../node_modules/.pnpm/mjml@4.14.1/node_modules/mjml/lib/index.js
../../node_modules/.pnpm/@faire+mjml-react@3.2.0_react@18.2.0/node_modules/@faire/mjml-react/utils/render.js
../../packages/emails/src/emails/AlmostReachedChatsLimitEmail.tsx
../../packages/emails/src/emails/index.ts
../../packages/emails/src/index.ts
./src/features/auth/helpers/sendVerificationRequest.ts
./src/pages/api/auth/[...nextauth].ts

../../node_modules/.pnpm/mjml-core@4.14.1/node_modules/mjml-core/lib/helpers/mjmlconfig.js
Critical dependency: the request of a dependency is an expression

Import trace for requested module:
../../node_modules/.pnpm/mjml-core@4.14.1/node_modules/mjml-core/lib/helpers/mjmlconfig.js
../../node_modules/.pnpm/mjml-core@4.14.1/node_modules/mjml-core/lib/index.js
../../node_modules/.pnpm/mjml@4.14.1/node_modules/mjml/lib/index.js
../../node_modules/.pnpm/@faire+mjml-react@3.2.0_react@18.2.0/node_modules/@faire/mjml-react/utils/render.js
../../packages/emails/src/emails/AlmostReachedChatsLimitEmail.tsx
../../packages/emails/src/emails/index.ts
../../packages/emails/src/index.ts
./src/features/auth/helpers/sendVerificationRequest.ts
./src/pages/api/auth/[...nextauth].ts

../../node_modules/.pnpm/mjml-core@4.14.1/node_modules/mjml-core/lib/helpers/mjmlconfig.js
Critical dependency: the request of a dependency is an expression

Import trace for requested module:
../../node_modules/.pnpm/mjml-core@4.14.1/node_modules/mjml-core/lib/helpers/mjmlconfig.js
../../node_modules/.pnpm/mjml-core@4.14.1/node_modules/mjml-core/lib/index.js
../../node_modules/.pnpm/mjml@4.14.1/node_modules/mjml/lib/index.js
../../node_modules/.pnpm/@faire+mjml-react@3.2.0_react@18.2.0/node_modules/@faire/mjml-react/utils/render.js
../../packages/emails/src/emails/AlmostReachedChatsLimitEmail.tsx
../../packages/emails/src/emails/index.ts
../../packages/emails/src/index.ts
./src/features/auth/helpers/sendVerificationRequest.ts
./src/pages/api/auth/[...nextauth].ts

../../node_modules/.pnpm/mjml-core@4.14.1/node_modules/mjml-core/lib/helpers/mjmlconfig.js
Critical dependency: the request of a dependency is an expression

Import trace for requested module:
../../node_modules/.pnpm/mjml-core@4.14.1/node_modules/mjml-core/lib/helpers/mjmlconfig.js
../../node_modules/.pnpm/mjml-core@4.14.1/node_modules/mjml-core/lib/index.js
../../node_modules/.pnpm/mjml@4.14.1/node_modules/mjml/lib/index.js
../../node_modules/.pnpm/@faire+mjml-react@3.2.0_react@18.2.0/node_modules/@faire/mjml-react/utils/render.js
../../packages/emails/src/emails/AlmostReachedChatsLimitEmail.tsx
../../packages/emails/src/emails/index.ts
../../packages/emails/src/index.ts
./src/features/auth/helpers/sendVerificationRequest.ts
./src/pages/api/auth/[...nextauth].ts

../../node_modules/.pnpm/mjml-core@4.14.1/node_modules/mjml-core/lib/index.js
Critical dependency: the request of a dependency is an expression

Import trace for requested module:
../../node_modules/.pnpm/mjml-core@4.14.1/node_modules/mjml-core/lib/index.js
../../node_modules/.pnpm/mjml@4.14.1/node_modules/mjml/lib/index.js
../../node_modules/.pnpm/@faire+mjml-react@3.2.0_react@18.2.0/node_modules/@faire/mjml-react/utils/render.js
../../packages/emails/src/emails/AlmostReachedChatsLimitEmail.tsx
../../packages/emails/src/emails/index.ts
../../packages/emails/src/index.ts
./src/features/auth/helpers/sendVerificationRequest.ts
./src/pages/api/auth/[...nextauth].ts

../../node_modules/.pnpm/node-fetch@2.6.9/node_modules/node-fetch/lib/index.js
Module not found: Can't resolve 'encoding' in '/home/omen/Traleor/typebot.io/node_modules/.pnpm/node-fetch@2.6.9/node_modules/node-fetch/lib'

Import trace for requested module:
../../node_modules/.pnpm/node-fetch@2.6.9/node_modules/node-fetch/lib/index.js
../../node_modules/.pnpm/web-resource-inliner@6.0.1/node_modules/web-resource-inliner/src/util.js
../../node_modules/.pnpm/web-resource-inliner@6.0.1/node_modules/web-resource-inliner/src/html.js
../../node_modules/.pnpm/web-resource-inliner@6.0.1/node_modules/web-resource-inliner/src/inline.js
../../node_modules/.pnpm/juice@9.0.0/node_modules/juice/index.js
../../node_modules/.pnpm/mjml-core@4.14.1/node_modules/mjml-core/lib/index.js
../../node_modules/.pnpm/mjml@4.14.1/node_modules/mjml/lib/index.js
../../node_modules/.pnpm/@faire+mjml-react@3.2.0_react@18.2.0/node_modules/@faire/mjml-react/utils/render.js
../../packages/emails/src/emails/AlmostReachedChatsLimitEmail.tsx
../../packages/emails/src/emails/index.ts
../../packages/emails/src/index.ts
./src/features/auth/helpers/sendVerificationRequest.ts
./src/pages/api/auth/[...nextauth].ts

../../node_modules/.pnpm/mjml-core@4.14.1/node_modules/mjml-core/lib/helpers/mjmlconfig.js
Critical dependency: the request of a dependency is an expression

Import trace for requested module:
../../node_modules/.pnpm/mjml-core@4.14.1/node_modules/mjml-core/lib/helpers/mjmlconfig.js
../../node_modules/.pnpm/mjml-core@4.14.1/node_modules/mjml-core/lib/index.js
../../node_modules/.pnpm/mjml@4.14.1/node_modules/mjml/lib/index.js
../../node_modules/.pnpm/@faire+mjml-react@3.2.0_react@18.2.0/node_modules/@faire/mjml-react/utils/render.js
../../packages/emails/src/emails/AlmostReachedChatsLimitEmail.tsx
../../packages/emails/src/emails/index.ts
../../packages/emails/src/index.ts

../../node_modules/.pnpm/mjml-core@4.14.1/node_modules/mjml-core/lib/helpers/mjmlconfig.js
Critical dependency: the request of a dependency is an expression

Import trace for requested module:
../../node_modules/.pnpm/mjml-core@4.14.1/node_modules/mjml-core/lib/helpers/mjmlconfig.js
../../node_modules/.pnpm/mjml-core@4.14.1/node_modules/mjml-core/lib/index.js
../../node_modules/.pnpm/mjml@4.14.1/node_modules/mjml/lib/index.js
../../node_modules/.pnpm/@faire+mjml-react@3.2.0_react@18.2.0/node_modules/@faire/mjml-react/utils/render.js
../../packages/emails/src/emails/AlmostReachedChatsLimitEmail.tsx
../../packages/emails/src/emails/index.ts
../../packages/emails/src/index.ts

../../node_modules/.pnpm/mjml-core@4.14.1/node_modules/mjml-core/lib/helpers/mjmlconfig.js
Critical dependency: the request of a dependency is an expression

Import trace for requested module:
../../node_modules/.pnpm/mjml-core@4.14.1/node_modules/mjml-core/lib/helpers/mjmlconfig.js
../../node_modules/.pnpm/mjml-core@4.14.1/node_modules/mjml-core/lib/index.js
../../node_modules/.pnpm/mjml@4.14.1/node_modules/mjml/lib/index.js
../../node_modules/.pnpm/@faire+mjml-react@3.2.0_react@18.2.0/node_modules/@faire/mjml-react/utils/render.js
../../packages/emails/src/emails/AlmostReachedChatsLimitEmail.tsx
../../packages/emails/src/emails/index.ts
../../packages/emails/src/index.ts

../../node_modules/.pnpm/mjml-core@4.14.1/node_modules/mjml-core/lib/helpers/mjmlconfig.js
Critical dependency: the request of a dependency is an expression

Import trace for requested module:
../../node_modules/.pnpm/mjml-core@4.14.1/node_modules/mjml-core/lib/helpers/mjmlconfig.js
../../node_modules/.pnpm/mjml-core@4.14.1/node_modules/mjml-core/lib/index.js
../../node_modules/.pnpm/mjml@4.14.1/node_modules/mjml/lib/index.js
../../node_modules/.pnpm/@faire+mjml-react@3.2.0_react@18.2.0/node_modules/@faire/mjml-react/utils/render.js
../../packages/emails/src/emails/AlmostReachedChatsLimitEmail.tsx
../../packages/emails/src/emails/index.ts
../../packages/emails/src/index.ts

../../node_modules/.pnpm/mjml-core@4.14.1/node_modules/mjml-core/lib/index.js
Critical dependency: the request of a dependency is an expression

Import trace for requested module:
../../node_modules/.pnpm/mjml-core@4.14.1/node_modules/mjml-core/lib/index.js
../../node_modules/.pnpm/mjml@4.14.1/node_modules/mjml/lib/index.js
../../node_modules/.pnpm/@faire+mjml-react@3.2.0_react@18.2.0/node_modules/@faire/mjml-react/utils/render.js
../../packages/emails/src/emails/AlmostReachedChatsLimitEmail.tsx
../../packages/emails/src/emails/index.ts
../../packages/emails/src/index.ts

../../node_modules/.pnpm/node-fetch@2.6.9/node_modules/node-fetch/lib/index.js
Module not found: Can't resolve 'encoding' in '/home/omen/Traleor/typebot.io/node_modules/.pnpm/node-fetch@2.6.9/node_modules/node-fetch/lib'

Import trace for requested module:
../../node_modules/.pnpm/node-fetch@2.6.9/node_modules/node-fetch/lib/index.js
../../node_modules/.pnpm/web-resource-inliner@6.0.1/node_modules/web-resource-inliner/src/util.js
../../node_modules/.pnpm/web-resource-inliner@6.0.1/node_modules/web-resource-inliner/src/html.js
../../node_modules/.pnpm/web-resource-inliner@6.0.1/node_modules/web-resource-inliner/src/inline.js
../../node_modules/.pnpm/juice@9.0.0/node_modules/juice/index.js
../../node_modules/.pnpm/mjml-core@4.14.1/node_modules/mjml-core/lib/index.js
../../node_modules/.pnpm/mjml@4.14.1/node_modules/mjml/lib/index.js
../../node_modules/.pnpm/@faire+mjml-react@3.2.0_react@18.2.0/node_modules/@faire/mjml-react/utils/render.js
../../packages/emails/src/emails/AlmostReachedChatsLimitEmail.tsx
../../packages/emails/src/emails/index.ts
../../packages/emails/src/index.ts

info  - Collecting page data ...TypeError: Cannot read properties of undefined (reading '1')
    at isFileType (node:fs:218:19)
    at Object.readFileSync (node:fs:472:16)
    at /home/omen/Traleor/typebot.io/apps/builder/.next/server/chunks/8979.js:92552:19
    at Array.map (<anonymous>)
    at /home/omen/Traleor/typebot.io/apps/builder/.next/server/chunks/8979.js:92551:30
    at 798 (/home/omen/Traleor/typebot.io/apps/builder/.next/server/chunks/8979.js:92556:2)
    at __webpack_require__ (/home/omen/Traleor/typebot.io/apps/builder/.next/server/webpack-runtime.js:25:43)
    at 4453 (/home/omen/Traleor/typebot.io/apps/builder/.next/server/chunks/8979.js:25748:16)
    at __webpack_require__ (/home/omen/Traleor/typebot.io/apps/builder/.next/server/webpack-runtime.js:25:43)
    at 4162 (/home/omen/Traleor/typebot.io/apps/builder/.next/server/chunks/8979.js:1511:25)

> Build error occurred
Error: Failed to collect page data for /
    at /home/omen/Traleor/typebot.io/node_modules/.pnpm/next@13.3.4_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/build/utils.js:1152:15
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  type: 'Error'
}
info  - Creating an optimized production build .info  - Collecting page data . ELIFECYCLE  Command failed with exit code 1.

```

**Comment by baptisteArno** [comment]
Have you ran `pnpm install` before re-building it?

**Comment by itzomen** [comment]
Yes I did 🤧

**Comment by baptisteArno** [comment]
That's strange... Can you try to delete `node_modules` folders, `pnpm-lock.yaml` and `apps/builder/.next` run install again and try again?

**Comment by itzomen** [comment]
Works like charm, thanks

😅I spent a whole day trying to figure out what I was doing wrong
