### ISSUE TITLE
Typebot instance stopped working after upgrade to v2.13.3

### ISSUE THREAD

**Issue by arladmin** [baptisteArno/typebot.io#516]
Self-hosted docker instance.

Logs:
**DB-**
```
PostgreSQL Database directory appears to contain a database; Skipping initialization
2023-05-17 08:20:50.110 UTC [1] LOG:  starting PostgreSQL 13.11 (Debian 13.11-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
2023-05-17 08:20:50.113 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2023-05-17 08:20:50.113 UTC [1] LOG:  listening on IPv6 address "::", port 5432
2023-05-17 08:20:50.118 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2023-05-17 08:20:50.125 UTC [27] LOG:  database system was shut down at 2023-05-17 08:20:37 UTC
2023-05-17 08:20:50.145 UTC [1] LOG:  database system is ready to accept connections
2023-05-17 08:22:49.464 UTC [36] FATAL:  password authentication failed for user "postgres"
2023-05-17 08:22:49.464 UTC [36] DETAIL:  Password does not match for user "postgres".
	Connection matched pg_hba.conf line 99: "host all all all md5"
2023-05-17 08:23:00.293 UTC [38] ERROR:  column Workspace.isQuarantined does not exist at character 150
2023-05-17 08:23:00.293 UTC [38] STATEMENT:  SELECT "public"."Workspace"."id", "public"."Workspace"."plan", "public"."Workspace"."additionalChatsIndex", "public"."Workspace"."customChatsLimit", "public"."Workspace"."isQuarantined" FROM "public"."Workspace" WHERE "public"."Workspace"."id" IN ($1) OFFSET $2
2023-05-17 08:26:03.238 UTC [42] FATAL:  password authentication failed for user "postgres"
2023-05-17 08:26:03.238 UTC [42] DETAIL:  Password does not match for user "postgres".
	Connection matched pg_hba.conf line 99: "host all all all md5"stening on IPv4 address "0.0.0.0", port 5432
```

**Builder-**
```
env.sh done
Checking if required environment variables are set and valid...
ENCRYPTION_SECRET is not 32 characters long. Exiting... (To generate a valid secret: https://docs.typebot.io/self-hosting/docker#2-add-the-required-configuration)
env.sh loaded
Matched inline env:
NEXT_PUBLIC_SMTP_FROM='Typebot Notifications' <typebot@my-domain>
NEXT_PUBLIC_VIEWER_URL=https://bot.tools.my-domain
Reading ./apps/builder/.env.production...
NEXT_PUBLIC_VIEWER_URL=https://bot.tools.my-domain
NEXT_PUBLIC_SMTP_FROM='Typebot Notifications' <typebot@my-domain>
NEXT_PUBLIC_GOOGLE_API_KEY=
NEXT_PUBLIC_GIPHY_API_KEY=
NEXT_PUBLIC_STRIPE_PUBLIC_KEY=
NEXT_PUBLIC_SENTRY_DSN=
NEXT_PUBLIC_VIEWER_INTERNAL_URL=
NEXT_PUBLIC_E2E_TEST=
NEXT_PUBLIC_VERCEL_VIEWER_PROJECT_NAME=
NEXT_PUBLIC_UNSPLASH_APP_NAME=
NEXT_PUBLIC_UNSPLASH_ACCESS_KEY=
NEXT_PUBLIC_SMTP_FROM='Typebot Notifications' <typebot@my-domain>
NEXT_PUBLIC_VIEWER_URL=https://bot.tools.my-domain
Got index from inline env: 0, replacing NEXT_PUBLIC_SMTP_FROM
Got index from inline env: 1, replacing NEXT_PUBLIC_VIEWER_URL
env.sh done
Checking if required environment variables are set and valid...
ENCRYPTION_SECRET is not 32 characters long. Exiting... (To generate a valid secret: https://docs.typebot.io/self-hosting/docker#2-add-the-required-configuration)
env.sh loaded
Matched inline env:
NEXT_PUBLIC_SMTP_FROM='Typebot Notifications' <typebot@my-domain>
NEXT_PUBLIC_VIEWER_URL=https://bot.tools.my-domain
Reading ./apps/builder/.env.production...
NEXT_PUBLIC_VIEWER_URL=https://bot.tools.my-domain
NEXT_PUBLIC_SMTP_FROM='Typebot Notifications' <typebot@my-domain>
NEXT_PUBLIC_GOOGLE_API_KEY=
NEXT_PUBLIC_GIPHY_API_KEY=
NEXT_PUBLIC_STRIPE_PUBLIC_KEY=
NEXT_PUBLIC_SENTRY_DSN=
NEXT_PUBLIC_VIEWER_INTERNAL_URL=
NEXT_PUBLIC_E2E_TEST=
NEXT_PUBLIC_VERCEL_VIEWER_PROJECT_NAME=
NEXT_PUBLIC_UNSPLASH_APP_NAME=
NEXT_PUBLIC_UNSPLASH_ACCESS_KEY=
NEXT_PUBLIC_SMTP_FROM='Typebot Notifications' <typebot@my-domain>
NEXT_PUBLIC_VIEWER_URL=https://bot.tools.my-domain
Got index from inline env: 0, replacing NEXT_PUBLIC_SMTP_FROM
Got index from inline env: 1, replacing NEXT_PUBLIC_VIEWER_URL
env.sh done
Checking if required environment variables are set and valid...
ENCRYPTION_SECRET is not 32 characters long. Exiting... (To generate a valid secret: https://docs.typebot.io/self-hosting/docker#2-add-the-required-configuration)
env.sh loaded
Matched inline env:
NEXT_PUBLIC_SMTP_FROM='Typebot Notifications' <typebot@my-domain>
NEXT_PUBLIC_VIEWER_URL=https://bot.tools.my-domain
Reading ./apps/builder/.env.production...
NEXT_PUBLIC_VIEWER_URL=https://bot.tools.my-domain
NEXT_PUBLIC_SMTP_FROM='Typebot Notifications' <typebot@my-domain>
NEXT_PUBLIC_GOOGLE_API_KEY=
NEXT_PUBLIC_GIPHY_API_KEY=
NEXT_PUBLIC_STRIPE_PUBLIC_KEY=
NEXT_PUBLIC_SENTRY_DSN=
NEXT_PUBLIC_VIEWER_INTERNAL_URL=
NEXT_PUBLIC_E2E_TEST=
NEXT_PUBLIC_VERCEL_VIEWER_PROJECT_NAME=
NEXT_PUBLIC_UNSPLASH_APP_NAME=
NEXT_PUBLIC_UNSPLASH_ACCESS_KEY=
NEXT_PUBLIC_SMTP_FROM='Typebot Notifications' <typebot@my-domain>
NEXT_PUBLIC_VIEWER_URL=https://bot.tools.my-domain
Got index from inline env: 0, replacing NEXT_PUBLIC_SMTP_FROM
Got index from inline env: 1, replacing NEXT_PUBLIC_VIEWER_URL
env.sh done
Checking if required environment variables are set and valid...
ENCRYPTION_SECRET is not 32 characters long. Exiting... (To generate a valid secret: https://docs.typebot.io/self-hosting/docker#2-add-the-required-configuration)
env.sh loaded
Matched inline env:
NEXT_PUBLIC_SMTP_FROM='Typebot Notifications' <typebot@my-domain>
NEXT_PUBLIC_VIEWER_URL=https://bot.tools.my-domain
Reading ./apps/builder/.env.production...
NEXT_PUBLIC_VIEWER_URL=https://bot.tools.my-domain
NEXT_PUBLIC_SMTP_FROM='Typebot Notifications' <typebot@my-domain>
NEXT_PUBLIC_GOOGLE_API_KEY=
NEXT_PUBLIC_GIPHY_API_KEY=
NEXT_PUBLIC_STRIPE_PUBLIC_KEY=
NEXT_PUBLIC_SENTRY_DSN=
NEXT_PUBLIC_VIEWER_INTERNAL_URL=
NEXT_PUBLIC_E2E_TEST=
NEXT_PUBLIC_VERCEL_VIEWER_PROJECT_NAME=
NEXT_PUBLIC_UNSPLASH_APP_NAME=
NEXT_PUBLIC_UNSPLASH_ACCESS_KEY=
NEXT_PUBLIC_SMTP_FROM='Typebot Notifications' <typebot@my-domain>
NEXT_PUBLIC_VIEWER_URL=https://bot.tools.my-domain
Got index from inline env: 0, replacing NEXT_PUBLIC_SMTP_FROM
Got index from inline env: 1, replacing NEXT_PUBLIC_VIEWER_URL
env.sh done
Checking if required environment variables are set and valid...
ENCRYPTION_SECRET is not 32 characters long. Exiting... (To generate a valid secret: https://docs.typebot.io/self-hosting/docker#2-add-the-required-configuration)
```

**Viewer-**
```
2023-05-17T08:20:49.943154005Z env.sh loaded
2023-05-17T08:20:49.972651496Z Matched inline env:
2023-05-17T08:20:49.972681311Z NEXT_PUBLIC_SMTP_FROM='Typebot Notifications' <typebot-email>
2023-05-17T08:20:49.972686030Z NEXT_PUBLIC_VIEWER_URL=https://bot.my-domain
2023-05-17T08:20:49.980570614Z Reading ./apps/viewer/.env.production...
2023-05-17T08:20:49.988193626Z NEXT_PUBLIC_VIEWER_URL=
2023-05-17T08:20:49.994545812Z NEXT_PUBLIC_E2E_TEST=
2023-05-17T08:20:50.005016466Z NEXT_PUBLIC_SMTP_FROM='Typebot Notifications' <typebot-email>
2023-05-17T08:20:50.005048013Z NEXT_PUBLIC_VIEWER_URL=https://bot.my-domain
2023-05-17T08:20:50.005414954Z Got index from inline env: 0, replacing NEXT_PUBLIC_SMTP_FROM
2023-05-17T08:20:50.011127091Z Got index from inline env: 1, replacing NEXT_PUBLIC_VIEWER_URL
2023-05-17T08:20:50.028506626Z env.sh done
2023-05-17T08:20:50.028554021Z 
2023-05-17T08:20:51.008566797Z Prisma schema loaded from packages/prisma/postgresql/schema.prisma
2023-05-17T08:20:52.304817538Z 
2023-05-17T08:20:52.304867605Z ✔ Generated Prisma Client (4.13.0 | library) to ./node_modules/.pnpm/@prisma+client@4.13.0_prisma@4.13.0/node_modules/@prisma/client in 736ms
2023-05-17T08:20:52.304875229Z You can now start using Prisma Client in your code. Reference: https://pris.ly/d/client
2023-05-17T08:20:52.304878779Z ```
2023-05-17T08:20:52.304882100Z import { PrismaClient } from '@prisma/client'
2023-05-17T08:20:52.304885240Z const prisma = new PrismaClient()
2023-05-17T08:20:52.304888363Z ```
2023-05-17T08:20:52.816149064Z info  - Loaded env from /app/apps/viewer/.env.production
2023-05-17T08:20:52.853813478Z Listening on port 3000 url: http://4ca13cd7a7e7:3000
2023-05-17T08:22:59.687912334Z (node:111) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.
2023-05-17T08:22:59.687967330Z 
2023-05-17T08:22:59.687971847Z Please migrate your code to use AWS SDK for JavaScript (v3).
2023-05-17T08:22:59.687975297Z For more information, check the migration guide at https://a.co/7PzMCcy
2023-05-17T08:22:59.687978604Z (Use `node --trace-warnings ...` to show where the warning was created)
2023-05-17T08:23:00.304885445Z Something went wrong Error: 
2023-05-17T08:23:00.304929209Z Invalid `prisma.publicTypebot.findFirst()` invocation:
2023-05-17T08:23:00.304933767Z 
2023-05-17T08:23:00.304937287Z 
2023-05-17T08:23:00.304940607Z The column `Workspace.isQuarantined` does not exist in the current database.
2023-05-17T08:23:00.304944332Z     at pn.handleRequestError (/app/node_modules/.pnpm/@prisma+client@4.13.0_prisma@4.13.0/node_modules/@prisma/client/runtime/library.js:176:6477)
2023-05-17T08:23:00.304948026Z     ... 8 lines matching cause stack trace ...
2023-05-17T08:23:00.304976553Z     at async outputMiddleware (file:///app/node_modules/.pnpm/@trpc+server@10.23.0/node_modules/@trpc/server/dist/index.mjs:297:24) {
2023-05-17T08:23:00.304980626Z   code: 'INTERNAL_SERVER_ERROR',
2023-05-17T08:23:00.304984012Z   name: 'TRPCError',
2023-05-17T08:23:00.304987394Z   [cause]: PrismaClientKnownRequestError: 
2023-05-17T08:23:00.304990877Z   Invalid `prisma.publicTypebot.findFirst()` invocation:
2023-05-17T08:23:00.304994004Z   
2023-05-17T08:23:00.304996795Z   
2023-05-17T08:23:00.304999671Z   The column `Workspace.isQuarantined` does not exist in the current database.
2023-05-17T08:23:00.305002142Z       at pn.handleRequestError (/app/node_modules/.pnpm/@prisma+client@4.13.0_prisma@4.13.0/node_modules/@prisma/client/runtime/library.js:176:6477)
2023-05-17T08:23:00.305004414Z       at pn.handleAndLogRequestError (/app/node_modules/.pnpm/@prisma+client@4.13.0_prisma@4.13.0/node_modules/@prisma/client/runtime/library.js:176:5907)
2023-05-17T08:23:00.305006697Z       at pn.request (/app/node_modules/.pnpm/@prisma+client@4.13.0_prisma@4.13.0/node_modules/@prisma/client/runtime/library.js:176:5786)
2023-05-17T08:23:00.305009005Z       at async t._request (/app/node_modules/.pnpm/@prisma+client@4.13.0_prisma@4.13.0/node_modules/@prisma/client/runtime/library.js:179:10484)
2023-05-17T08:23:00.305011226Z       at async getTypebot (/app/apps/viewer/.next/server/pages/api/v1/[...trpc].js:2544:10)
2023-05-17T08:23:00.305013343Z       at async startSession (/app/apps/viewer/.next/server/pages/api/v1/[...trpc].js:2456:21)
2023-05-17T08:23:00.305015920Z       at async /app/apps/viewer/.next/server/pages/api/v1/[...trpc].js:2415:114
2023-05-17T08:23:00.305018049Z       at async resolveMiddleware (file:///app/node_modules/.pnpm/@trpc+server@10.23.0/node_modules/@trpc/server/dist/index.mjs:416:30)
2023-05-17T08:23:00.305020150Z       at async callRecursive (file:///app/node_modules/.pnpm/@trpc+server@10.23.0/node_modules/@trpc/server/dist/index.mjs:452:32)
2023-05-17T08:23:00.305022303Z       at async outputMiddleware (file:///app/node_modules/.pnpm/@trpc+server@10.23.0/node_modules/@trpc/server/dist/index.mjs:297:24) {
2023-05-17T08:23:00.305024449Z     code: 'P2022',
2023-05-17T08:23:00.305026519Z     clientVersion: '4.13.0',
2023-05-17T08:23:00.305030097Z     meta: { column: 'Workspace.isQuarantined' }
2023-05-17T08:23:00.305033153Z   }
2023-05-17T08:23:00.305035994Z }
```

Currently, one of the main errors that i see is the ENCRYPTION_SECRET one. But i'm not sure if it possible to change it now, in a running production instance, or is it?

Also, what's the cause of the other issues? The instance had been working fine until just before i upgraded it.

**Comment by baptisteArno** [comment]
Indeed, you should not change the encryption secret.

I wonder why it doesn't pass the check here (#500). Any chance you can provide your encryption secret after changing several characters to similar ones? Send it to baptiste@typebot.io
