### ISSUE TITLE
Chatwoot Identity validation

### ISSUE THREAD

**Issue by arthurbarret0** [baptisteArno/typebot.io#524]
Add the possibility to validate the user's identity (native Chatwoot function) when the chatwoot is loaded by Typebot.

https://www.chatwoot.com/docs/product/channels/live-chat/sdk/identity-validation/

**Comment by baptisteArno** [comment]
Duplicate of #519

**Comment by arthurbarret0** [comment]
> Duplicate of #519

My first suggestion is to implement identity validation in Typebot. This new suggestion, refers to deploying chatwoot identity validation to the chatwoot widget loaded by typebot.

As it currently stands: If a conversation is started in chatwoot via the widget loaded by typebot, chatwoot will display a warning that that user's identity has not been validated.

That is, even if identity validation is deployed in typebot, there will be a need to deploy chatwoot identity validation to the chatwoot widget.

Translated with www.DeepL.com/Translator (free version)

**Comment by lazmo88** [comment]
Not sure if directly related to this feature request, but it seems that if you now pass email to Chatwoot block (under Chatwoot > Set user details > Email) there is following error:

```
Script threw an error: SyntaxError: Unexpected identifier 'vauukqwjms0io0m6f9m382ciz'
    at AsyncFunction (<anonymous>)
    at pl (375.7b512aed1d84014a.js:1:254525)
    at yl (375.7b512aed1d84014a.js:1:256178)
    at Object.g (375.7b512aed1d84014a.js:1:265189)
```

Above error causes the Chatwoot widget loading to fail. If I remove the email from user details, the Chatwoot widget loads correctly.

**Comment by lazmo88** [comment]
> Not sure if directly related to this feature request, but it seems that if you now pass email to Chatwoot block (under Chatwoot > Set user details > Email) there is following error:
> 
> ```
> Script threw an error: SyntaxError: Unexpected identifier 'vauukqwjms0io0m6f9m382ciz'
>     at AsyncFunction (<anonymous>)
>     at pl (375.7b512aed1d84014a.js:1:254525)
>     at yl (375.7b512aed1d84014a.js:1:256178)
>     at Object.g (375.7b512aed1d84014a.js:1:265189)
> ```
> 
> Above error causes the Chatwoot widget loading to fail. If I remove the email from user details, the Chatwoot widget loads correctly.

Ok, so it seems it is not Chatwoot related. For some reason all my variables when passed to script block and/or to built-in blocks seems to display random string such as "vl6rh3yei06i4ie6fzvbt05zm". These variables renders fine on the chat widget, but when passing to script block or Chatwoot they get random value. It almost seems like that the {{email}} returns internal variable "label" than actual "value". Ill raise another issue about this as it is not related to Chatwoot identity validation.

**Comment by baptisteArno** [comment]
Typebot is now in maintenance mode, so I’m no longer planning new features, product improvements or large internal projects. I’m closing this to keep the issue tracker focused on bugs, security and compatibility. Thanks for the suggestion!
