### ISSUE TITLE
Self host emails are not getting triggered 

### ISSUE THREAD

**Issue by cherrycharan** [baptisteArno/typebot.io#581]
I have selfhosted typebot and i am unable to send emails where i am getting 500 internal server error when checked in network tab of the browser and when checked the container logs found the below 

```
(node:171) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.

Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check the migration guide at https://a.co/7PzMCcy
(Use `node --trace-warnings ...` to show where the warning was created)
Error: Missing credentials for "PLAIN"
    at SMTPConnection._formatError (/app/node_modules/.pnpm/nodemailer@6.9.2/node_modules/nodemailer/lib/smtp-connection/index.js:790:19)
    at SMTPConnection.login (/app/node_modules/.pnpm/nodemailer@6.9.2/node_modules/nodemailer/lib/smtp-connection/index.js:444:38)
    at /app/node_modules/.pnpm/nodemailer@6.9.2/node_modules/nodemailer/lib/smtp-transport/index.js:272:32
    at SMTPConnection.<anonymous> (/app/node_modules/.pnpm/nodemailer@6.9.2/node_modules/nodemailer/lib/smtp-connection/index.js:213:17)
    at Object.onceWrapper (node:events:627:28)
    at SMTPConnection.emit (node:events:513:28)
    at SMTPConnection.emit (node:domain:489:12)
    at SMTPConnection._actionEHLO (/app/node_modules/.pnpm/nodemailer@6.9.2/node_modules/nodemailer/lib/smtp-connection/index.js:1331:14)
    at SMTPConnection._processResponse (/app/node_modules/.pnpm/nodemailer@6.9.2/node_modules/nodemailer/lib/smtp-connection/index.js:953:20)
    at SMTPConnection._onData (/app/node_modules/.pnpm/nodemailer@6.9.2/node_modules/nodemailer/lib/smtp-connection/index.js:755:14) {
  code: 'EAUTH',
  command: 'API'
}
```

**Comment by baptisteArno** [comment]
Can you share your SMTP config?

**Comment by cherrycharan** [comment]
`- SMTP_HOST=smtp.zoho.in
      - SMTP_PORT=587
      - SMTP_USER=email@domain.com
      - SMTP_PASSWORD=mypass
      - SMTP_FROM=email@mydomain.com
      - SMTP_REPLY_TO=email@mydomain.com
      - NEXT_PUBLIC_SMTP_FROM='Bot' <email@mydomain.com>
      - SMTP_AUTH_DISABLED=false
      - SMTP_SECURE=false`
      
      @baptisteArno  above is the config i used

**Comment by cherrycharan** [comment]
I made a mistake with - SMTP_USER where it should be - SMTP_USERNAME
