### ISSUE TITLE
" Error! Couldn't initiate the chat. " & " The bot you're looking for doesn't exist. "

### ISSUE THREAD

**Issue by jdefranco** [baptisteArno/typebot.io#621]
Getting Error! " Couldn't initiate the chat. " in the builder... see screencapture :
https://www.awesomescreenshot.com/video/19260032?key=2a1a5382c6b15a64a9e37456196dceda

and getting " 404 The bot you're looking for doesn't exist. " trying to go to the viewer page or the chatbot url after publishing and sharing a bot

**Comment by baptisteArno** [comment]
Did you correctly set the `NEXT_PUBLIC_VIEWER_URL` variable? Is the viewer (https://docs.typebot.io/self-hosting/configuration/builder)

**Comment by jdefranco** [comment]
**** addresses being used
builder: typebot-builder-teal.vercel.app
viewer : typebot-io-viewer-phi.vercel.app

**Comment by jdefranco** [comment]
here is the log from the viewer :

TypeError: Cannot read properties of undefined (reading 'split')
    at /var/task/apps/viewer/.next/server/pages/[[...publicId]].js:121:201
    at Array.some (<anonymous>)
    at getServerSideProps (/var/task/apps/viewer/.next/server/pages/[[...publicId]].js:121:143)
    at /var/task/node_modules/.pnpm/next@13.4.3_@babel+core@7.21.8_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/render.js:565:26
    at /var/task/node_modules/.pnpm/next@13.4.3_@babel+core@7.21.8_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/lib/trace/tracer.js:113:36
    at NoopContextManager.with (/var/task/node_modules/.pnpm/next@13.4.3_@babel+core@7.21.8_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:7057)
    at ContextAPI.with (/var/task/node_modules/.pnpm/next@13.4.3_@babel+core@7.21.8_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:516)
    at NoopTracer.startActiveSpan (/var/task/node_modules/.pnpm/next@13.4.3_@babel+core@7.21.8_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:18086)
    at ProxyTracer.startActiveSpan (/var/task/node_modules/.pnpm/next@13.4.3_@babel+core@7.21.8_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:18847)
    at /var/task/node_modules/.pnpm/next@13.4.3_@babel+core@7.21.8_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/lib/trace/tracer.js:102:107



and here is a log from the builder:
[GET] /typebots/clk9zda440001l9083sv0dar8/typebot-io-viewer-phi.vercel.app/api/v1/sendMessage
Status code : 404
Host: typebot-builder-teal.vercel.app

**Comment by baptisteArno** [comment]
Can you share a screenshot of your `NEXT_PUBLIC_VIEWER_URL` env in the builder project?

**Comment by jdefranco** [comment]
![typebot-builder-–-Environment-Variables-Vercel](https://github.com/baptisteArno/typebot.io/assets/45438667/6a1ed06f-760e-4934-a3e2-e3918bbc320f)

 attached screenshot

**Comment by jdefranco** [comment]
got it working, urls were missing the https://

**Comment by Lanhild** [comment]
@baptisteArno having that same error. Both variables are set correctly according to the documentation. My instance is deployed on docker.

Had the issue happen once today, never before nor after, but the weird thing is that there are no relevant logs, so I can't provide much more information.

To investigate, if it happens again I'll let you know

**Comment by baptisteArno** [comment]
You can set the `DEBUG` variable to `true` in the viewer to get more relevant logs to debug this 🙏

For now I'm closing this issue as it's resolved for its creator
