### ISSUE TITLE
Some installed packages in the node_modules folder went disappeared after I run the pnpm run build in the builder folder 

### ISSUE THREAD

**Issue by BenHugh** [baptisteArno/typebot.io#661]
It works well after I run the pnpm install and pnpm run build in the root folder for the first time.
But if I changed something and wanted to run the pnpm run build command in the builder folder or the viewer folder again, some installed packages become empty in the node_modules folder ( in the builder and viewer folder).
Has anyone ever encountered this kind of scenario ?

**Comment by baptisteArno** [comment]
Can you tell us exactly what is the issue and how we can reproduce it step by step?

**Comment by BenHugh** [comment]
Because I'm running it on my localhost, so I changed the build stript in the package.json file to 'next build'. And change the postgresql localpath to my own database.
Then, run pnpm install, pnpm run build:builder, sometimes it will fail, so rerun pnpm install, and rerun pnpm run build:builder, then some folders in the node_modles of the builder app will just become empty, like next.
Don't know what happened.

**Comment by baptisteArno** [comment]
We can't help without any error message. Can you provide details about this?

**Comment by BenHugh** [comment]
Sorry, when I change something I wanna rerun the 'pnpm run build:builder' command again, then this error will be showing.

```
@typebot.io/prisma:db:generate: cache bypass, force executing d37ee7c7b32d0185
@typebot.io/prisma:db:generate: 
@typebot.io/prisma:db:generate: > @typebot.io/prisma@0.1.0 db:generate E:\Workshop\NextJs\typebotSecond\packages\prisma
@typebot.io/prisma:db:generate: > tsx scripts/db-generate.ts
@typebot.io/prisma:db:generate:
@typebot.io/prisma:db:generate: Executing for PostgreSQL schema
@typebot.io/prisma:db:generate: Environment variables loaded from .env
@typebot.io/prisma:db:generate: Prisma schema loaded from postgresql\schema.prisma
@typebot.io/prisma:db:generate:
@typebot.io/prisma:db:generate: ✔ Generated Prisma Client (5.0.0 | library) to .\..\..\node_modules\.pnpm\@prisma+client@5.0.0_prisma@5.0.0\node_modules\@prisma\client in 286ms
@typebot.io/prisma:db:generate: You can now start using Prisma Client in your code. Reference: https://pris.ly/d/client
@typebot.io/prisma:db:generate: ```
@typebot.io/prisma:db:generate: import { PrismaClient } from '@prisma/client'
@typebot.io/prisma:db:generate: const prisma = new PrismaClient()
@typebot.io/prisma:db:generate: ```
@typebot.io/prisma:db:generate:
@typebot.io/js:build: cache hit, suppressing logs aa623415280953ff
@typebot.io/react:build: cache hit, suppressing logs 92fb49b75e722812
@typebot.io/nextjs:build: cache hit, suppressing logs 9d89933c95db6083
builder:build: cache miss, executing 5fa1c3b2a61f7cdd
builder:build: 
builder:build: > builder@0.1.0 build E:\Workshop\NextJs\typebotSecond\apps\builder
builder:build: > next build
builder:build:
builder:build: - info Loaded env from E:\Workshop\NextJs\typebotSecond\apps\builder\.env.local
builder:build: - warn You have enabled experimental feature (outputFileTracingRoot) in next.config.js.
builder:build: - warn Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use at your own risk.
builder:build:
builder:build: - info Linting and checking validity of types...
builder:build: - info Creating an optimized production build...
builder:build: 
builder:build: > Build error occurred
builder:build: Error: Cannot find module './impl'
builder:build: Require stack:
builder:build: - E:\Workshop\NextJs\typebotSecond\node_modules\.pnpm\next@13.4.3_@babel+core@7.22.9_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\build\webpack-build\index.js
builder:build: - E:\Workshop\NextJs\typebotSecond\node_modules\.pnpm\next@13.4.3_@babel+core@7.22.9_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\build\index.js 
builder:build: - E:\Workshop\NextJs\typebotSecond\node_modules\.pnpm\next@13.4.3_@babel+core@7.22.9_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\cli\next-build.js
builder:build: - E:\Workshop\NextJs\typebotSecond\node_modules\.pnpm\next@13.4.3_@babel+core@7.22.9_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\lib\commands.js
builder:build: - E:\Workshop\NextJs\typebotSecond\node_modules\.pnpm\next@13.4.3_@babel+core@7.22.9_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\bin\next       
builder:build:     at Module._resolveFilename (node:internal/modules/cjs/loader:1048:15)
builder:build:     at E:\Workshop\NextJs\typebotSecond\node_modules\.pnpm\next@13.4.3_@babel+core@7.22.9_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\server\require-hook.js:180:36
builder:build:     at Module._load (node:internal/modules/cjs/loader:901:27)
builder:build:     at Module.require (node:internal/modules/cjs/loader:1115:19)
builder:build:     at require (node:internal/modules/helpers:119:18)
builder:build:     at webpackBuild (E:\Workshop\NextJs\typebotSecond\node_modules\.pnpm\next@13.4.3_@babel+core@7.22.9_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\build\webpack-build\index.js:136:34)
builder:build:     at E:\Workshop\NextJs\typebotSecond\node_modules\.pnpm\next@13.4.3_@babel+core@7.22.9_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\build\index.js:559:160
builder:build:     at async Span.traceAsyncFn (E:\Workshop\NextJs\typebotSecond\node_modules\.pnpm\next@13.4.3_@babel+core@7.22.9_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\trace\trace.js:103:20)
builder:build:     at async build (E:\Workshop\NextJs\typebotSecond\node_modules\.pnpm\next@13.4.3_@babel+core@7.22.9_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\build\index.js:145:29) {
builder:build:   code: 'MODULE_NOT_FOUND',
builder:build:   requireStack: [
builder:build:     'E:\\Workshop\\NextJs\\typebotSecond\\node_modules\\.pnpm\\next@13.4.3_@babel+core@7.22.9_react-dom@18.2.0_react@18.2.0\\node_modules\\next\\dist\\build\\webpack-build\\index.js',
builder:build:     'E:\\Workshop\\NextJs\\typebotSecond\\node_modules\\.pnpm\\next@13.4.3_@babel+core@7.22.9_react-dom@18.2.0_react@18.2.0\\node_modules\\next\\dist\\build\\index.js',
builder:build:     'E:\\Workshop\\NextJs\\typebotSecond\\node_modules\\.pnpm\\next@13.4.3_@babel+core@7.22.9_react-dom@18.2.0_react@18.2.0\\node_modules\\next\\dist\\cli\\next-build.js',
builder:build:     'E:\\Workshop\\NextJs\\typebotSecond\\node_modules\\.pnpm\\next@13.4.3_@babel+core@7.22.9_react-dom@18.2.0_react@18.2.0\\node_modules\\next\\dist\\lib\\commands.js',
builder:build:     'E:\\Workshop\\NextJs\\typebotSecond\\node_modules\\.pnpm\\next@13.4.3_@babel+core@7.22.9_react-dom@18.2.0_react@18.2.0\\node_modules\\next\\dist\\bin\\next'
```

If I rerun the same command again,  'pnpm run build:builder' , I noticed some folder under node_modules just become empty, like the 'next', 'next-auth', and some other folders around them, maybe these folders just become empty after I rerun this command the first time.

Then, it will show me another error, like this, 

```
uilder:build: cache miss, executing 5fa1c3b2a61f7cdd
builder:build: 
builder:build: > builder@0.1.0 build E:\Workshop\NextJs\typebotSecond\apps\builder
builder:build: > next build
builder:build:
builder:build: node:internal/modules/cjs/loader:1051
builder:build:   throw err;
builder:build:   ^
builder:build:
builder:build: Error: Cannot find module 'E:\Workshop\NextJs\typebotSecond\apps\builder\node_modules\next\dist\bin\next'
builder:build:     at Module._resolveFilename (node:internal/modules/cjs/loader:1048:15)
builder:build:     at Module._load (node:internal/modules/cjs/loader:901:27)
builder:build:     at node:internal/main/run_main_module:23:47 {
builder:build:   code: 'MODULE_NOT_FOUND',
builder:build:   requireStack: []
builder:build: }
builder:build:
builder:build: Node.js v20.4.0
builder:build:  ELIFECYCLE  Command failed with exit code 1.
builder:build: ERROR: command finished with error: command (E:\Workshop\NextJs\typebotSecond\apps\builder) pnpm run build exited (1)    
command (E:\Workshop\NextJs\typebotSecond\apps\builder) pnpm run build exited (1)
```

It looks like I am only allowed to run the build command only once, or I did something wrong.

**Comment by BenHugh** [comment]
After the folders become empty, if I delete the node_modules folder and rerun the 'pnpm install ' command,  there folders still are empty,

**Comment by baptisteArno** [comment]
I'm actually clueless here 🤔

Can you use `pnpm run build:apps` instead of `pnpm run build:builder`? Does that help?

**Comment by BenHugh** [comment]
Actually I can produce this very easily, I only run the builder part
1. Follow the instructions outlined in the [Typebot self-hosting manual](https://docs.typebot.io/self-hosting/manual).
2. Once your localhost server is up and running, you can easily make changes by adding console logs or modifying any part of the code.
3. After you've made your changes, execute pnpm run build:builder again to rebuild the builder part of your project.
4. As a result of step 3, you might notice that some folders within the node_modules directory, specifically those located under app/builder, have become empty.

Is it correct to rebuild the builder part code in this way ?
