### ISSUE TITLE
Error! Couldn't initiate the chat.

### ISSUE THREAD

**Issue by Eliseu2023** [baptisteArno/typebot.io#701]
I'm not sure what else to do. I've tried over 4 installations, but there's no way around this error "Error! Couldn't initiate the chat." I'm looking forward to any solutions from you guys.

**Comment by frmilani** [comment]
I'm having the same problem here. I revised and installed it again about 5 times but I still had no success, always the same error in the Viewer

**Comment by baptisteArno** [comment]
Hey Baptistearno/Typebot.Io,Thank you for reaching out! This is an automated reply just to tell you that I received your message and will process it ASAP.Feel free to send any more information so that I can help you faster 💪

**Comment by baptisteArno** [comment]
Can you share a URL so that we can see the error and debug properly?

Also, sharing the server logs would be helpful.

**Comment by megapaulo8** [comment]
Try use the command to docker compose down and then upgrade your server memory (ssd or hd), sometimes left space in your server memory, it works to me until now.

**Comment by frmilani** [comment]
Thanks baptisteArno and megapaulo8, problem solved, really after reviewing the installation update everything working perfectly.

**Comment by montenegromatheus** [comment]
I'm having the same problem, what did you do @frmilani ?

**Comment by ildo19** [comment]
TAMBEM TENHO O MESMO PROBLEMA

**Comment by megapaulo8** [comment]
É falta de armazenamento em disco esse problema, a não ser que o chat tenha sido removido.
Is not enough memory (ssd or hd), or you have removed the chat.

**Comment by crediflex** [comment]
Como consigo resolver esse problema? Qual seria o comando para ser usado no terminal BitViser?

**Comment by rogercg7** [comment]
https://www.youtube.com/watch?v=IJqq8vdxs5k

> Como consigo resolver esse problema? Qual seria o comando para ser usado no terminal BitViser?

**Comment by renelourenco** [comment]
My server memory is ok and I'm having this error :(

**Comment by baptisteArno** [comment]
CHECK SERVER LOGS TO SEE THE ISSUE: `docker-compose logs`

**Comment by stgdigital** [comment]
I'm having this problem and `docker-compose logs` shows this:

```bash
typebot-viewer_1   | Error: Invalid environment variables: {"NEXTAUTH_URL":["Required"]}
typebot-viewer_1   |     at onValidationError (/app/apps/viewer/.next/server/chunks/195.js:1:8134)
typebot-viewer_1   |     at /app/apps/viewer/.next/server/chunks/851.js:1:1063
typebot-viewer_1   |     at h (/app/apps/viewer/.next/server/chunks/851.js:1:1250)
typebot-viewer_1   |     at 12629 (/app/apps/viewer/.next/server/chunks/195.js:1:7491)
typebot-viewer_1   |     at __webpack_require__ (/app/apps/viewer/.next/server/webpack-api-runtime.js:1:161)
typebot-viewer_1   |     at 8195 (/app/apps/viewer/.next/server/chunks/195.js:1:8378)
typebot-viewer_1   |     at __webpack_require__ (/app/apps/viewer/.next/server/webpack-api-runtime.js:1:161)
typebot-viewer_1   |     at 6150 (/app/apps/viewer/.next/server/chunks/487.js:1:8900)
typebot-viewer_1   |     at __webpack_require__ (/app/apps/viewer/.next/server/webpack-api-runtime.js:1:161)
typebot-viewer_1   |     at /app/apps/viewer/.next/server/pages/api/v1/[...trpc].js:1:4169
```

I don't understand this error, as my `docker-compose.yml` was configured with the `NEXTAUTH_URL`

**Comment by stgdigital** [comment]
I just check my `docker-compose logs` and the problem was that the `NEXTAUTH_URL` was only specified on the `typebot-builder` and it was missing on the `typebot-viewer`. Now that I declared it and ran the compose again it's working fine.

**Comment by rafaelbarrosNT** [comment]
> I just check my `docker-compose logs` and the problem was that the `NEXTAUTH_URL` was only specified on the `typebot-builder` and it was missing on the `typebot-viewer`. Now that I declared it and ran the compose again it's working fine.

This solved the problem for me. Tanks

**Comment by BLTinvest** [comment]
**The problem persists, I've already edited the domain in the viewer and builder and it still doesn't work** HELP-ME


- event [next-runtime-env] read environment variables prefixed with 'NEXT_PUBLIC_' from process.env.

- ready [next-runtime-env] wrote browser runtime environment variables to '/app/apps/viewer/public/__ENV.js'.

▲ Next.js 13.5.4

- Local:        http://localhost:3000/

- Network:      http://0.0.0.0:3000/

✓ Ready in 68ms

**Comment by BLTinvest** [comment]
The problem persists, I've already edited the domain in the viewer and builder and it still doesn't work HELP-ME

event [next-runtime-env] read environment variables prefixed with 'NEXT_PUBLIC_' from process.env.

ready [next-runtime-env] wrote browser runtime environment variables to '/app/apps/viewer/public/__ENV.js'.

▲ Next.js 13.5.4

Local: http://localhost:3000/

Network: http://0.0.0.0:3000/

✓ Ready in 68ms

**Comment by antoniomatheus26** [comment]
I'm using Elestio and I'm having this same problem. Would anyone know how to solve it?

**Comment by jmempreendedorismo** [comment]
**Easypanel:**

Go to your typebot project, in the 'typebot-builder' part (left menu), then:

1. in the "Envirionment" tab, copy the line starting with:
NEXTAUTH_URL=https://.... (your domain)

Now in the 'typebot-viewer' part, in the "Environment" tab and below
DATABASE_URL=postgres://postgres....

2. Paste the command line you copied from 1. "Typebot-builder"
Like this:
![ERROR-4](https://github.com/baptisteArno/typebot.io/assets/152125146/d7af6383-d19a-472f-9065-52166b1d8ad8)

This way, in the 'typebot-viewer' part, you will have access to the typebot front-end.

3. Check turn On, the option: Create .env file

In Buttons in 'typebot-builder' and 'typebot-viwer' 
4.  Force Rebuild.
After click:
5. Stop.
After:
6. Start.

**Comment by songjinghe** [comment]
same as @jmempreendedorismo in Easypanel, I install typebot from CapRover, also encounter this error, I sovle this by checking & setting ALL env variables in `typebot-viewer` & `typebot-builder` app correctly, do not leave empty string for any variable. check console log first.

**Comment by fabiocavalcantem** [comment]
> **Easypanel:**
> 
> Go to your typebot project, in the 'typebot-builder' part (left menu), then:
> 
> 1. in the "Envirionment" tab, copy the line starting with:
>    NEXTAUTH_URL=https://.... (your domain)
> 
> Now in the 'typebot-viewer' part, in the "Environment" tab and below DATABASE_URL=postgres://postgres....
> 
> 2. Paste the command line you copied from 1. "Typebot-builder"
>    Like this:
>    ![ERROR-4](https://private-user-images.githubusercontent.com/152125146/285725767-d7af6383-d19a-472f-9065-52166b1d8ad8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4OTIzODIsIm5iZiI6MTcxOTg5MjA4MiwicGF0aCI6Ii8xNTIxMjUxNDYvMjg1NzI1NzY3LWQ3YWY2MzgzLWQxOWEtNDcyZi05MDY1LTUyMTY2YjFkOGFkOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwMlQwMzQ4MDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ZmJkNjI3NGUwOWMzNGZjMzkyY2MxN2FmN2I1NGZlN2RjY2ZlMWFkY2I1MDU4MzU5NjljODMyNGFhMTJmZjJlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.YXco166AnwPvKeKr9cuhcT8yzm-EMb8ba1c6t04UL98)
> 
> This way, in the 'typebot-viewer' part, you will have access to the typebot front-end.
> 
> 3. Check turn On, the option: Create .env file
> 
> In Buttons in 'typebot-builder' and 'typebot-viwer' 4. Force Rebuild. After click: 5. Stop. After: 6. Start.


@jmempreendedorismo  funcionou aqui. Valeu!
This solved the problem for me, thank you!
