### ISSUE TITLE
Google Auth Error: Can't Sign in , error expected 200 OK, got: 403 Forbidden.

### ISSUE THREAD

**Issue by luizeof** [baptisteArno/typebot.io#723]
I am getting an error message when configuring Google Auth.

I have checked the configuration data several times and it agrees with the documentation.

Found this bug on the next-auth lib:

https://github.com/nextauthjs/next-auth/discussions/8323

ERROR LOG (builder):

```
env.sh loaded
Matched inline env:
NEXT_PUBLIC_SMTP_FROM='Typebot' <REDACTED@REDACTED>
NEXT_PUBLIC_VIEWER_URL=https://REDACTED
Reading ./apps/builder/.env.production...
NEXT_PUBLIC_VIEWER_URL=
NEXT_PUBLIC_SMTP_FROM=
NEXT_PUBLIC_GOOGLE_API_KEY=
NEXT_PUBLIC_GIPHY_API_KEY=
NEXT_PUBLIC_STRIPE_PUBLIC_KEY=
NEXT_PUBLIC_SENTRY_DSN=
NEXT_PUBLIC_VIEWER_INTERNAL_URL=
NEXT_PUBLIC_E2E_TEST=
NEXT_PUBLIC_VERCEL_VIEWER_PROJECT_NAME=
NEXT_PUBLIC_UNSPLASH_APP_NAME=
NEXT_PUBLIC_UNSPLASH_ACCESS_KEY=
NEXT_PUBLIC_ONBOARDING_TYPEBOT_ID=
NEXT_PUBLIC_SMTP_FROM='Typebot' <REDACTED@REDACTED>
NEXT_PUBLIC_VIEWER_URL=https://REDACTED
Got index from inline env: 0, replacing NEXT_PUBLIC_SMTP_FROM
Got index from inline env: 1, replacing NEXT_PUBLIC_VIEWER_URL
env.sh done
Checking if required environment variables are set and valid...
Prisma schema loaded from packages/prisma/postgresql/schema.prisma
✔ Generated Prisma Client (5.0.0 | library) to ./node_modules/.pnpm/@prisma+client@5.0.0_prisma@5.0.0/node_modules/@prisma/client in 623ms
You can now start using Prisma Client in your code. Reference: https://pris.ly/d/client
Waiting 5s for db to be ready...
Prisma schema loaded from packages/prisma/postgresql/schema.prisma
Datasource "db": PostgreSQL database "typebotnggpsat", schema "public" at "postgres:5432"
54 migrations found in prisma/migrations
No pending migrations to apply.
- info Loaded env from /app/apps/builder/.env.production
Listening on port 3000 url: http://1805201c9716:3000
- info Loaded env from /app/apps/builder/.env.production
(node:180) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.
Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check the migration guide at https://a.co/7PzMCcy
(Use `node --trace-warnings ...` to show where the warning was created)
[next-auth][error][OAUTH_CALLBACK_ERROR] 
https://next-auth.js.org/errors#oauth_callback_error expected 200 OK, got: 403 Forbidden {
  error: OPError: expected 200 OK, got: 403 Forbidden
      at processResponse (/app/node_modules/.pnpm/openid-client@5.4.2/node_modules/openid-client/lib/helpers/process_response.js:41:11)
      at /app/node_modules/.pnpm/openid-client@5.4.2/node_modules/openid-client/lib/helpers/issuer.js:47:22
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async Issuer.queryKeyStore (/app/node_modules/.pnpm/openid-client@5.4.2/node_modules/openid-client/lib/helpers/issuer.js:83:20)
      at async Client.validateJWT (/app/node_modules/.pnpm/openid-client@5.4.2/node_modules/openid-client/lib/client.js:1035:14)
      at async Client.validateIdToken (/app/node_modules/.pnpm/openid-client@5.4.2/node_modules/openid-client/lib/client.js:745:49)
      at async Client.callback (/app/node_modules/.pnpm/openid-client@5.4.2/node_modules/openid-client/lib/client.js:488:7)
      at async oAuthCallback (/app/node_modules/.pnpm/next-auth@4.22.1_next@13.4.3_nodemailer@6.9.3_react-dom@18.2.0_react@18.2.0/node_modules/next-auth/core/lib/oauth/callback.js:109:16)
      at async Object.callback (/app/node_modules/.pnpm/next-auth@4.22.1_next@13.4.3_nodemailer@6.9.3_react-dom@18.2.0_react@18.2.0/node_modules/next-auth/core/routes/callback.js:52:11)
      at async AuthHandler (/app/node_modules/.pnpm/next-auth@4.22.1_next@13.4.3_nodemailer@6.9.3_react-dom@18.2.0_react@18.2.0/node_modules/next-auth/core/index.js:208:28) {
    name: 'OAuthCallbackError',
    code: undefined
  },
  providerId: 'google',
  message: 'expected 200 OK, got: 403 Forbidden'
}
```

**Comment by baptisteArno** [comment]
Can you maybe share screenshots of your Google console config? I can't really guess what's wrong here :/

**Comment by LucioArtes** [comment]
> Você pode compartilhar capturas de tela da configuração do console do Google? Eu realmente não consigo adivinhar o que há de errado aqui :/

Here it is

https://github.com/LucioArtes/imagens/blob/main/CleanShot%202023-08-29%20at%2013.39.21%402x.png

https://github.com/LucioArtes/imagens/blob/main/CleanShot%202023-08-29%20at%2015.21.38%402x.png

**Comment by baptisteArno** [comment]
Do you confirm that you try to login with one the user listed in the test users list?

**Comment by LucioArtes** [comment]
> Do you confirm that you try to login with one the user listed in the test users list?

Yes.
I tried with several emails registered as a test and the error is always the same.|

https://github.com/LucioArtes/imagens/blob/main/CleanShot%202023-08-30%20at%2013.23.24%402x.png

https://github.com/LucioArtes/imagens/blob/main/CleanShot%202023-08-30%20at%2013.25.51%402x.png

https://github.com/LucioArtes/imagens/blob/main/CleanShot%202023-08-30%20at%2013.31.15%402x.png

**Comment by baptisteArno** [comment]
Google returns 403 for some reason I don't know.

Triple check your env variables:`GOOGLE_CLIENT_ID` and `GOOGLE_CLIENT_SECRET`. Regenerate the secret if possible.

Other than this, I can't help more 🤔 as it's not an issue with Typebot.

**Comment by baptisteArno** [comment]
Typebot uses NextAuth under the hood. And you can check the config here:

https://github.com/baptisteArno/typebot.io/blob/efd4600b7eea86f33c39365c5269ccc727d9b8c3/apps/builder/src/pages/api/auth/%5B...nextauth%5D.ts

If you find anything useful, let us know 🙏
