### ISSUE TITLE
Unable to use storage (minio) in localhost

### ISSUE THREAD

**Issue by beckrafael** [baptisteArno/typebot.io#761]
This call return error `{"message":"connect ECONNREFUSED 127.0.0.1:9000","code":"INTERNAL_SERVER_ERROR"}`

### Http POST
```
curl 'http://localhost:8081/api/v1/sendMessage' \
  -H 'Accept: */*' \
  -H 'Accept-Language: en-US,en;q=0.9,pt-BR;q=0.8,pt;q=0.7,es;q=0.6' \
  -H 'Connection: keep-alive' \
  -H 'Content-Type: application/json' \
  -H 'Origin: http://localhost:8081' \
  -H 'Referer: http://localhost:8081/bot01' \
  -H 'Sec-Fetch-Dest: empty' \
  -H 'Sec-Fetch-Mode: cors' \
  -H 'Sec-Fetch-Site: same-origin' \
  -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36' \
  -H 'sec-ch-ua: "Chromium";v="116", "Not)A;Brand";v="24", "Google Chrome";v="116"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "Windows"' \
  --data-raw '{"sessionId":"clm50ys5s0000pf35ak46y3q2","message":"http://localhost:9000/typebot/public/results/k6k6ubiju2zynee4lmlj6kth/bcy77kagrr5ijd0f17p8s969/06-lin60.jpg"}' \
  --compressed
```

The file is created in minio service and this url is working fine on browser:
http://localhost:9000/typebot/public/results/k6k6ubiju2zynee4lmlj6kth/bcy77kagrr5ijd0f17p8s969/06-lin60.jpg

### Container error
```
msg-typebot-viewer-1   | - info Loaded env from /app/apps/viewer/.env.production
msg-typebot-viewer-1   | (node:113) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.
msg-typebot-viewer-1   |
msg-typebot-viewer-1   | Please migrate your code to use AWS SDK for JavaScript (v3).
msg-typebot-viewer-1   | For more information, check the migration guide at https://a.co/7PzMCcy
msg-typebot-viewer-1   | (Use `node --trace-warnings ...` to show where the warning was created)
msg-typebot-viewer-1   | Something went wrong RequestError: connect ECONNREFUSED 127.0.0.1:9000
msg-typebot-viewer-1   |     at ClientRequest.<anonymous> (file:///app/node_modules/.pnpm/got@12.6.0/node_modules/got/dist/source/core/index.js:789:107)
msg-typebot-viewer-1   |     ... 9 lines matching cause stack trace ...
msg-typebot-viewer-1   |     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1495:16) {
msg-typebot-viewer-1   |   code: 'INTERNAL_SERVER_ERROR',
msg-typebot-viewer-1   |   name: 'TRPCError',
msg-typebot-viewer-1   |   [cause]: RequestError: connect ECONNREFUSED 127.0.0.1:9000
msg-typebot-viewer-1   |       at ClientRequest.<anonymous> (file:///app/node_modules/.pnpm/got@12.6.0/node_modules/got/dist/source/core/index.js:789:107)
msg-typebot-viewer-1   |       at Object.onceWrapper (node:events:629:26)
msg-typebot-viewer-1   |       at ClientRequest.emit (node:events:526:35)
msg-typebot-viewer-1   |       at ClientRequest.emit (node:domain:489:12)
msg-typebot-viewer-1   |       at Socket.socketErrorListener (node:_http_client:501:9)
msg-typebot-viewer-1   |       at Socket.emit (node:events:514:28)
msg-typebot-viewer-1   |       at Socket.emit (node:domain:489:12)
msg-typebot-viewer-1   |       at emitErrorNT (node:internal/streams/destroy:151:8)
msg-typebot-viewer-1   |       at emitErrorCloseNT (node:internal/streams/destroy:116:3)
msg-typebot-viewer-1   |       at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
msg-typebot-viewer-1   |       at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1495:16) {
msg-typebot-viewer-1   |     input: undefined,
msg-typebot-viewer-1   |     code: 'ECONNREFUSED',
msg-typebot-viewer-1   |     timings: {
msg-typebot-viewer-1   |       start: 1693840625909,
msg-typebot-viewer-1   |       socket: 1693840625909,
msg-typebot-viewer-1   |       lookup: 1693840625909,
msg-typebot-viewer-1   |       connect: undefined,
msg-typebot-viewer-1   |       secureConnect: undefined,
msg-typebot-viewer-1   |       upload: undefined,
msg-typebot-viewer-1   |       response: undefined,
msg-typebot-viewer-1   |       end: undefined,
msg-typebot-viewer-1   |       error: 1693840625909,
msg-typebot-viewer-1   |       abort: undefined,
msg-typebot-viewer-1   |       phases: [Object]
msg-typebot-viewer-1   |     },
msg-typebot-viewer-1   |     options: {
msg-typebot-viewer-1   |       request: undefined,
msg-typebot-viewer-1   |       agent: { http: undefined, https: undefined, http2: undefined },
msg-typebot-viewer-1   |       h2session: undefined,
msg-typebot-viewer-1   |       decompress: true,
msg-typebot-viewer-1   |       timeout: {
msg-typebot-viewer-1   |         connect: undefined,
msg-typebot-viewer-1   |         lookup: undefined,
msg-typebot-viewer-1   |         read: undefined,
msg-typebot-viewer-1   |         request: undefined,
msg-typebot-viewer-1   |         response: undefined,
msg-typebot-viewer-1   |         secureConnect: undefined,
msg-typebot-viewer-1   |         send: undefined,
msg-typebot-viewer-1   |         socket: undefined
msg-typebot-viewer-1   |       },
msg-typebot-viewer-1   |       prefixUrl: '',
msg-typebot-viewer-1   |       body: undefined,
msg-typebot-viewer-1   |       form: undefined,
msg-typebot-viewer-1   |       json: undefined,
msg-typebot-viewer-1   |       cookieJar: undefined,
msg-typebot-viewer-1   |       ignoreInvalidCookies: false,
msg-typebot-viewer-1   |       searchParams: undefined,
msg-typebot-viewer-1   |       dnsLookup: undefined,
msg-typebot-viewer-1   |       dnsCache: undefined,
msg-typebot-viewer-1   |       context: {},
msg-typebot-viewer-1   |       hooks: {
msg-typebot-viewer-1   |         init: [],
msg-typebot-viewer-1   |         beforeRequest: [],
msg-typebot-viewer-1   |         beforeError: [],
msg-typebot-viewer-1   |         beforeRedirect: [],
msg-typebot-viewer-1   |         beforeRetry: [],
msg-typebot-viewer-1   |         afterResponse: []
msg-typebot-viewer-1   |       },
msg-typebot-viewer-1   |       followRedirect: true,
msg-typebot-viewer-1   |       maxRedirects: 10,
msg-typebot-viewer-1   |       cache: undefined,
msg-typebot-viewer-1   |       throwHttpErrors: true,
msg-typebot-viewer-1   |       username: '',
msg-typebot-viewer-1   |       password: '',
msg-typebot-viewer-1   |       http2: false,
msg-typebot-viewer-1   |       allowGetBody: false,
msg-typebot-viewer-1   |       headers: {
msg-typebot-viewer-1   |         'user-agent': 'got (https://github.com/sindresorhus/got)',
msg-typebot-viewer-1   |         'accept-encoding': 'gzip, deflate, br'
msg-typebot-viewer-1   |       },
msg-typebot-viewer-1   |       methodRewriting: false,
msg-typebot-viewer-1   |       dnsLookupIpVersion: undefined,
msg-typebot-viewer-1   |       parseJson: [Function: parse],
msg-typebot-viewer-1   |       stringifyJson: [Function: stringify],
msg-typebot-viewer-1   |       retry: {
msg-typebot-viewer-1   |         limit: 2,
msg-typebot-viewer-1   |         methods: [ 'GET', 'PUT', 'HEAD', 'DELETE', 'OPTIONS', 'TRACE' ],
msg-typebot-viewer-1   |         statusCodes: [
msg-typebot-viewer-1   |           408, 413, 429, 500,
msg-typebot-viewer-1   |           502, 503, 504, 521,
msg-typebot-viewer-1   |           522, 524
msg-typebot-viewer-1   |         ],
msg-typebot-viewer-1   |         errorCodes: [
msg-typebot-viewer-1   |           'ETIMEDOUT',
msg-typebot-viewer-1   |           'ECONNRESET',
msg-typebot-viewer-1   |           'EADDRINUSE',
msg-typebot-viewer-1   |           'ECONNREFUSED',
msg-typebot-viewer-1   |           'EPIPE',
msg-typebot-viewer-1   |           'ENOTFOUND',
msg-typebot-viewer-1   |           'ENETUNREACH',
msg-typebot-viewer-1   |           'EAI_AGAIN'
msg-typebot-viewer-1   |         ],
msg-typebot-viewer-1   |         maxRetryAfter: undefined,
msg-typebot-viewer-1   |         calculateDelay: [Function: calculateDelay],
msg-typebot-viewer-1   |         backoffLimit: Infinity,
msg-typebot-viewer-1   |         noise: 100
msg-typebot-viewer-1   |       },
msg-typebot-viewer-1   |       localAddress: undefined,
msg-typebot-viewer-1   |       method: 'GET',
msg-typebot-viewer-1   |       createConnection: undefined,
msg-typebot-viewer-1   |       cacheOptions: {
msg-typebot-viewer-1   |         shared: undefined,
msg-typebot-viewer-1   |         cacheHeuristic: undefined,
msg-typebot-viewer-1   |         immutableMinTimeToLive: undefined,
msg-typebot-viewer-1   |         ignoreCargoCult: undefined
msg-typebot-viewer-1   |       },
msg-typebot-viewer-1   |       https: {
msg-typebot-viewer-1   |         alpnProtocols: undefined,
msg-typebot-viewer-1   |         rejectUnauthorized: undefined,
msg-typebot-viewer-1   |         checkServerIdentity: undefined,
msg-typebot-viewer-1   |         certificateAuthority: undefined,
msg-typebot-viewer-1   |         key: undefined,
msg-typebot-viewer-1   |         certificate: undefined,
msg-typebot-viewer-1   |         passphrase: undefined,
msg-typebot-viewer-1   |         pfx: undefined,
msg-typebot-viewer-1   |         ciphers: undefined,
msg-typebot-viewer-1   |         honorCipherOrder: undefined,
msg-typebot-viewer-1   |         minVersion: undefined,
msg-typebot-viewer-1   |         maxVersion: undefined,
msg-typebot-viewer-1   |         signatureAlgorithms: undefined,
msg-typebot-viewer-1   |         tlsSessionLifetime: undefined,
msg-typebot-viewer-1   |         dhparam: undefined,
msg-typebot-viewer-1   |         ecdhCurve: undefined,
msg-typebot-viewer-1   |         certificateRevocationLists: undefined
msg-typebot-viewer-1   |       },
msg-typebot-viewer-1   |       encoding: undefined,
msg-typebot-viewer-1   |       resolveBodyOnly: false,
msg-typebot-viewer-1   |       isStream: false,
msg-typebot-viewer-1   |       responseType: 'text',
msg-typebot-viewer-1   |       url: URL {
msg-typebot-viewer-1   |         href: 'http://localhost:9000/typebot/public/results/k6k6ubiju2zynee4lmlj6kth/bcy77kagrr5ijd0f17p8s969/06-lin60.jpg',
msg-typebot-viewer-1   |         origin: 'http://localhost:9000',
msg-typebot-viewer-1   |         protocol: 'http:',
msg-typebot-viewer-1   |         username: '',
msg-typebot-viewer-1   |         password: '',
msg-typebot-viewer-1   |         host: 'localhost:9000',
msg-typebot-viewer-1   |         hostname: 'localhost',
msg-typebot-viewer-1   |         port: '9000',
msg-typebot-viewer-1   |         pathname: '/typebot/public/results/k6k6ubiju2zynee4lmlj6kth/bcy77kagrr5ijd0f17p8s969/06-lin60.jpg',
msg-typebot-viewer-1   |         search: '',
msg-typebot-viewer-1   |         searchParams: URLSearchParams {},
msg-typebot-viewer-1   |         hash: ''
msg-typebot-viewer-1   |       },
msg-typebot-viewer-1   |       pagination: {
msg-typebot-viewer-1   |         transform: [Function: transform],
msg-typebot-viewer-1   |         paginate: [Function: paginate],
msg-typebot-viewer-1   |         filter: [Function: filter],
msg-typebot-viewer-1   |         shouldContinue: [Function: shouldContinue],
msg-typebot-viewer-1   |         countLimit: Infinity,
msg-typebot-viewer-1   |         backoff: 0,
msg-typebot-viewer-1   |         requestLimit: 10000,
msg-typebot-viewer-1   |         stackAllItems: false
msg-typebot-viewer-1   |       },
msg-typebot-viewer-1   |       setHost: true,
msg-typebot-viewer-1   |       maxHeaderSize: undefined,
msg-typebot-viewer-1   |       signal: undefined,
msg-typebot-viewer-1   |       enableUnixSockets: true
msg-typebot-viewer-1   |     }
msg-typebot-viewer-1   |   }
msg-typebot-viewer-1   | }
```

### My compose file
```
version: '3.3'
services:
  typebot-db:
    image: postgres:13
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - ${PWD}/.typebot/database:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=typebot
      - POSTGRES_PASSWORD=typebot
  typebot-builder:
    image: baptistearno/typebot-builder:latest
    restart: always
    depends_on:
      - typebot-db
    ports:
      - '8080:3000'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    env_file: .env
  typebot-viewer:
    image: baptistearno/typebot-viewer:latest
    restart: always
    ports:
      - '8081:3000'
    env_file: .env
  typebot-minio:
    image: minio/minio:latest
    ports:
      - '9000:9000'
      - '9001:9001'
    command: server --console-address ":9001" /data
    env_file: .env
```

### My .env file (partial)
```
S3_BUCKET=typebot
S3_PORT=9000
S3_ENDPOINT=localhost
S3_SSL=false
```

**Comment by baptisteArno** [comment]
Whenever you submit a file, it tries to read it to get its size.

When the viewer tries to read: http://localhost:9000/typebot/public/results/k6k6ubiju2zynee4lmlj6kth/bcy77kagrr5ijd0f17p8s969/06-lin60.jpg

He can't find it because http://localhost:9000 doesn't point to the minio instance.

You need instead something like: http://typebot-minio:9000/typebot/public/results/k6k6ubiju2zynee4lmlj6kth/bcy77kagrr5ijd0f17p8s969/06-lin60.jpg
