### ISSUE TITLE
Error on install

### ISSUE THREAD

**Issue by jordaoluiz** [baptisteArno/typebot.io#875]
- event [next-runtime-env] read environment variables prefixed with 'NEXT_PUBLIC_' from process.env.
- ready [next-runtime-env] wrote browser runtime environment variables to '/app/apps/viewer/public/__ENV.js'.
Listening on port 3000 url: http://448a2c4bd982:3000
❌ Invalid environment variables: { NEXTAUTH_URL: [ 'Required' ] }
❌ Invalid environment variables: { NEXTAUTH_URL: [ 'Required' ] }
Error: Invalid environment variables
    at T.m (/app/apps/viewer/.next/server/chunks/321.js:20787:575)
    at T (/app/apps/viewer/.next/server/chunks/321.js:20787:765)
    at P (/app/apps/viewer/.next/server/chunks/321.js:20787:1156)
    at /app/apps/viewer/.next/server/chunks/500.js:9289:83
Error: Invalid environment variables
    at T.m (/app/apps/viewer/.next/server/chunks/321.js:20787:575)
    at T (/app/apps/viewer/.next/server/chunks/321.js:20787:765)
    at P (/app/apps/viewer/.next/server/chunks/321.js:20787:1156)
    at /app/apps/viewer/.next/server/chunks/500.js:9289:83

i dont know how to solve it, my env variable is defined on docker-compose file

**Comment by baptisteArno** [comment]
It basically says that you forgot to set the `NEXTAUTH_URL` environment variable. 👍
