### ISSUE TITLE
How to resolve CORS typebot issue

### ISSUE THREAD

**Issue by devtest51** [baptisteArno/typebot.io#912]
Typebot is on the default port http://localhost:3000

but I'm making a request with ajax in a different environment that is at this url http://localhost/

the ajax code is this

```
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script type="text/javascript">
    $.ajax({
  url: 'http://localhost:3000/api/auth/signin/email',
  type: 'POST',
  headers: {
    'Content-Type': 'application/x-www-form-urlencoded',
  },
  data: {
    email: 'test@gmail.com',
    redirect: false,
    csrfToken: 'd48b8fabf408e01f5cb053e13232b2b5abcd78b790db59075abdc4ea9300aca2',
    callbackUrl: 'http://localhost:3000/signin',
    json: true,
  },
   xhrFields: {
    withCredentials: true
  },
  beforeSend: function(xhr) {
    // Defina o cookie no cabeçalho da solicitação
    xhr.setRequestHeader('Cookie', 'next-auth.csrf-token=d48b8fabf408e01f5cb053e13232b2b5abcd78b790db59075abdc4ea9300aca2%257C9db44ec855a4b182319a792a1a0eafe3df6a3bb3109c51819ba3ee525113c32a; next-auth.callback-url=http://localhost:3000/signin');
  },
  success: function(response) {
    // Ação a ser executada quando a solicitação for bem-sucedida
    console.log(response);
  },
  error: function(error) {
    // Ação a ser executada em caso de erro na solicitação
    console.error(error);
  },
});
</script>
```

![image](https://github.com/baptisteArno/typebot.io/assets/147625587/e6fee838-b78a-4a56-bbd6-f1b09ee10431)

How can I resolve this?
@baptisteArno

**Comment by baptisteArno** [comment]
I don't understand. Where do you put this code?

**Comment by devtest51** [comment]
> Eu não entendo. Onde você coloca esse código?

I made this code to send dynamic email and create a user.
I decided to change the code.

And this code is in a separate project.

When I run this code:

```
$curl = curl_init();

curl_setopt_array($curl, [
  CURLOPT_PORT => "3000",
  CURLOPT_URL => "http://localhost:3000/api/auth/signin/email",
  CURLOPT_RETURNTRANSFER => true,
  CURLOPT_ENCODING => "",
  CURLOPT_MAXREDIRS => 10,
  CURLOPT_TIMEOUT => 30,
  CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
  CURLOPT_CUSTOMREQUEST => "POST",
  CURLOPT_POSTFIELDS => "email=test%40gmail.com&redirect=false&csrfToken=e54d083bb3d857cfdc17461f529e2ad8654f16d6fc74df2f4f75a90e0cc7ed0b&callbackUrl=http%3A%2F%2Flocalhost%3A3000%2Fsignin&json=true",
  CURLOPT_COOKIE => "next-auth.csrf-token=ed34ae8ed01d3d8ce6c6d124d7da98471ca4465796b1cd3c1d1facfe71baf0ff%257Cd132057d53ad8824afd15408872ac358375c914bc7464323b21abf4bd072e901; next-auth.callback-url=http%253A%252F%252Flocalhost%253A3000%252Fsignin",
  CURLOPT_HTTPHEADER => [
    "Content-Type: application/x-www-form-urlencoded"
  ],
]);

$response = curl_exec($curl);
$err = curl_error($curl);

curl_close($curl);

if ($err) {
  echo "cURL Error #:" . $err;
} else {
  echo $response;
}
```

it returns this in the terminal

```
[next-auth][error][INVALID_CALLBACK_URL_ERROR]
https://next-auth.js.org/errors#invalid_callback_url_error Invalid callback URL. Received: http%3A%2F%2Flocalhost%3A3000%2Fsignin InvalidCallbackUrl: Invalid callback URL. Received: http%3A%2F%2Flocalhost%3A3000%2Fsignin
    at assertConfig (/home/dev/typebot/node_modules/.pnpm/next-auth@4.23.2_next@13.5.4_nodemailer@6.9.3_react-dom@18.2.0_react@18.2.0/node_modules/next-auth/core/lib/assert.js:62:12)
    at AuthHandler (/home/dev/typebot/node_modules/.pnpm/next-auth@4.23.2_next@13.5.4_nodemailer@6.9.3_react-dom@18.2.0_react@18.2.0/node_modules/next-auth/core/index.js:77:52)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async NextAuthApiHandler (/home/dev/typebot/node_modules/.pnpm/next-auth@4.23.2_next@13.5.4_nodemailer@6.9.3_react-dom@18.2.0_react@18.2.0/node_modules/next-auth/next/index.js:22:19)
    at async handler (/home/dev/typebot/apps/builder/.next/server/chunks/2063.js:1:8563) {
  code: 'INVALID_CALLBACK_URL_ERROR'
```


The idea is to be able to create a user dynamically, as it would already send the email directly to the user

como voce faria isso?
@baptisteArno

**Comment by devtest51** [comment]
When I test it with Postman, passing all the parameters it works, but when I implemented it into the code it didn't work


```
curl --request POST \
  --url http://localhost:3000/api/auth/signin/email \
  --header 'Content-Type: application/x-www-form-urlencoded' \
  --cookie 'next-auth.csrf-token=ed34ae8ed01d3d8ce6c6d124d7da98471ca4465796b1cd3c1d1facfe71baf0ff%257Cd132057d53ad8824afd15408872ac358375c914bc7464323b21abf4bd072e901; next-auth.callback-url=http%253A%252F%252Flocalhost%253A3000%252Fsignin' \
  --data email=test@gmail.com \
  --data redirect=false \
  --data csrfToken=e54d083bb3d857cfdc17461f529e2ad8654f16d6fc74df2f4f75a90e0cc7ed0b \
  --data callbackUrl=http://localhost:3000/signin \
  --data json=true
```

**Comment by baptisteArno** [comment]
I'm sorry but if it works with Postman, then your code has an issue and it's really out of Typebot scope 🙏
