### ISSUE TITLE
Error uploading images to digitalOceanSpaces storage. 

### ISSUE THREAD

**Issue by abdkelani** [baptisteArno/typebot.io#996]
I am facing an error when I try to upload any file. 

The error log I got from vercel is:

```
Something went wrong InvalidEndpointError: Invalid endPoint : https://*************.digitaloceanspaces.com
    at new TypedClient (/var/task/apps/builder/.next/server/chunks/3174.js:11:177574)
    ... 8 lines matching cause stack trace ...
    at async callRecursive (file:///var/task/node_modules/.pnpm/@trpc+server@10.40.0/node_modules/@trpc/server/dist/index.mjs:456:32) {
  code: 'INTERNAL_SERVER_ERROR',
  name: 'TRPCError',
  [cause]: InvalidEndpointError: Invalid endPoint : https://*************.digitaloceanspaces.com
      at new TypedClient (/var/task/apps/builder/.next/server/chunks/3174.js:11:177574)
      at new Client (/var/task/apps/builder/.next/server/chunks/3174.js:15:23602)
      at generatePresignedPostPolicy (/var/task/apps/builder/.next/server/chunks/6468.js:1:473)
      at /var/task/apps/builder/.next/server/chunks/533.js:1:62131
      at async resolveMiddleware (file:///var/task/node_modules/.pnpm/@trpc+server@10.40.0/node_modules/@trpc/server/dist/index.mjs:420:30)
      at async callRecursive (file:///var/task/node_modules/.pnpm/@trpc+server@10.40.0/node_modules/@trpc/server/dist/index.mjs:456:32)
      at async outputMiddleware (file:///var/task/node_modules/.pnpm/@trpc+server@10.40.0/node_modules/@trpc/server/dist/index.mjs:301:24)
      at async callRecursive (file:///var/task/node_modules/.pnpm/@trpc+server@10.40.0/node_modules/@trpc/server/dist/index.mjs:456:32)
      at async callRecursive (file:///var/task/node_modules/.pnpm/@trpc+server@10.40.0/node_modules/@trpc/server/dist/index.mjs:456:32)
      at async callRecursive (file:///var/task/node_modules/.pnpm/@trpc+server@10.40.0/node_modules/@trpc/server/dist/index.mjs:456:32)
}
```

I have set up the env variable like this: 

```
ENCRYPTION_SECRET=***********************

DATABASE_URL=**************************

NEXTAUTH_URL=https://*************************app

NEXT_PUBLIC_VIEWER_URL=************************.vercel.app

GITHUB_CLIENT_ID=***************************

GITHUB_CLIENT_SECRET=******************************

S3_ACCESS_KEY=****************************
S3_SECRET_KEY=****************************
S3_BUCKET=********
S3_ENDPOINT=https://***********.digitaloceanspaces.com/
```

**Comment by baptisteArno** [comment]
Remove `https://` from the endpoint value 🙏
